### ISSUE TITLE
Online Custom Filter List

### ISSUE THREAD

**Issue by lisandrocarmona** [safing/portmaster#1000]
**What would you like to add or change?**:
I wish we could add online custom filter lists, and not only local lists on txt files.

**Why do you and others need this?**:
As it will be impossible to add all available filter lists to fit all users' needs, adding online (and up-to-date) filter lists would be a great addition. Right now, Portmaster shows an error when we try to add a URL instead of a local file.

By the way, when we remove the URL, Portmaster continues to show the error and is kept into the yellow warning state, which seems to be an UI bug.

**Comment by Terrance** [comment]
I'd like to use [hagezi/dns-blocklists](https://github.com/hagezi/dns-blocklists) directly in Portmaster, and those lists update regularly so I don't particularly want to have to manage a local copy of it.

I can also confirm the sticky UI warning, as I originally pasted a blocklist URL into the Custom Filter List field expecting it to be an online source, and now clearing the field hasn't reset the warning.

(Not sure what other input I can provide to satisfy the label... can this be reopened @Raphty?)

**Comment by Raphty** [comment]
@Terrance, online lists are not planned, so the issue will stay closed. 

We are including a bunch of lists in Portmaster already and they update hourly!
I guess he is doing a similar thing to what we do, https://github.com/safing/intel-data/

I did check the repo, and I could not find a license, so we won't just include the list. If you can get in touch with the maintainer and ask if we can get a license to include his lists into Portmaster, then we can add it to our lists. Which is the preferred way, because it will allow more people to get this value automatically.

**Comment by Terrance** [comment]
> online lists are not planned

Noted -- it wasn't clear from the issue being closed with no response what the reasoning was, if it was just in need of more or fresh support etc.

It may be worth making it more obvious that this config option is for a local file, as the combination of the field being below selectable online lists, the field itself being text entry rather than file selection, and the "file path" hint being hidden in the info popup (and that hint being easy to overlook even there) led me to assume it would just be a URL.

> get in touch with the maintainer and ask if we can get a license to include his lists into Portmaster

It looks like the license in that repo has been questioned a few times already (most recently hagezi/dns-blocklists#1151 which led to the repo's overall license being removed), so I'm not there's likely to be any movement there.

For what it's worth, my main goal is just to have a single consistent filter list on all my devices (Windows, Linux, Android) -- I'm aware you maintain your own set of lists, though I assume Portmaster fetches the sources file and then downloads each selected list individually?

**Comment by Raphty** [comment]
https://wiki.safing.io/en/Portmaster/Architecture/PrivacyFilter#filter-lists-1

No. We collect the data from all the filter lists aggregate them and then your Portmaster only pulls the parts it needs
