### ISSUE TITLE
What are your plans of making pihole officially compatible with portmaster?

### ISSUE THREAD

**Issue by Kostrol** [safing/portmaster#1069]
**What would you like to add or change?**:
adding/putting pihole on the compatibility software list and making them work together without issues.

**Why do you and others need this?**:
Having portmaster protect your computer with applications while pihole protecting overall network makes for the perfect protection, no? not one to replace the other. Perhaps a collaboration effort?

**Comment by Raphty** [comment]
Hey there, yes PiHole is a tool many people use as well, and I agree that the focus is different so having both can be a good idea.

I don't personally run PiHole on my network, but I can give it a try and look if it works, I think it should work perfectly next to each other.

In regards to working together -  We are open to working together, but also have plans to extend Portmaster into managing more of your network. So ultimately we see a Portmaster replacement for PiHole. Which will be easier to manage for regular people - have more insights like what apps are creating the traffic, since it will integrate with local Portmaster - and make managing multiple devices in (for instance for a family) easier.

**Comment by Raphty** [comment]
we are always working on making our part as fast as possible, but of course going through multiple inbetweens before actually getting the answer to the dns request will have a time impact.

**Comment by Digital-ecologist** [comment]
Hi, I think I have a similar issue.
Recently set up a pi hole with goal adding extra security for Internet of things devices that can't have security on them directly. Figured it would also be a good idea for my laptops to benefit from both layers of security so I took a look at the documentation and added this line to my PortMaster DNS.

`dot://orangepipcplus?ip=192.168.X.XXX&name=Pi-hole&blockedif=empty`

My Linux Mint laptop seems to accept having this is the first entry without complaint or performance impact.
On Windows 10, it makes DNS resolution slow and temperamental often seeming to block DNS access altogether.

Did I constructed the DNS entry correctly? Is there a way to resolve this on Windows?
Unsure if this matters, but I'm using Quad9 as upstream on the pi hole, so I mimicked the syntax of the Quad9 entries in PortMaster.
