### ISSUE TITLE
Dose not work with EasyList 

### ISSUE THREAD

**Issue by otherside1** [safing/portmaster#1071]
EasyList  (https://easylist.to/easylist/easylist.txt) which is one of the most complete add block list gives errors when added to postmaster.

**Comment by vlabo** [comment]
This list is not in the proper format.
If you look in the popup help window you will see the description what should be the format.
```
The file (.txt) is checked every couple minutes and will be automatically reloaded when it has changed.

Entries (one per line) may be one of:

Domain: "example.com"
IP Address: "10.0.0.1"
Country Code (based on IP): "US"
AS (Autonomous System): "AS1234"
Everything after the first element of a line, comments starting with a '#', and empty lines are ignored.
The settings "Block Subdomains of Filter List Entries" and "Block Domain Aliases" also apply to the custom filter list.
Lists in the "Hosts" format are not supported.

Please note that the custom filter list is fully loaded into memory. This can have a negative impact on your device if big lists are loaded.
```

And easylist (from quick look of the website) is designed primarily for adblock software. Since Portmaster is firewall 
can block only things that can see domains and ip addresses

Portmaster can's see the https path of the request which is a big part of this blocklist.
