### ISSUE TITLE
Windows Firewall & Portmaster

### ISSUE THREAD

**Issue by LiberteIV** [safing/portmaster#1104]
This a question not an issue, is there any point in having the windows firewall enabled when portmaster is installed?

**Comment by Raphty** [comment]
Windows defender does more then just being a firewall, and we recommend leaving it on.

**Comment by Abyssgrowth** [comment]
> Windows defender does more then just being a firewall, and we recommend leaving it on.

Hello, i am also interested in this question.
Why do you recommend to keep windows firewall enabled while portmaster is installed?

**Comment by davegson** [comment]
see [**Should I use an Anti-Virus together with Portmaster?** #960](https://github.com/safing/portmaster/issues/960)

**Comment by davegson** [comment]
@Abyssgrowth since W10 Windows Firewall is officially called **Windows Defender Firewall**. I changed the FAQ to have the full name

**Comment by Baton34** [comment]
In the Windows settings, I can enable or disable virus protection and firewall separately. So I don't understand why I would need to enable the Windows Firewall while using Portmaster. This way they will do the same job of filtering network packets. Only when the firewall is disabled, Windows prompts me to turn it on every boot, which is annoying. Why is Portmaster not registered in the system as a firewall?

**Comment by Raphty** [comment]
Hey, @Baton34 thanks for the feedback.

Portmaster does not need to be registered as a firewall because we link directly into the kernel and don't need windows in between. Also the windows defender in its default config with both firewall and virus protection up works well with Portmaster so pleas just keep it as it is. less work for you and everyone else.
