### ISSUE TITLE
Add a name in the tray on KDE Linux

### ISSUE THREAD

**Issue by Zorrototo** [safing/portmaster#1106]
**What would you like to add or change?**: I installed Port Master from the AUR on Manjaro KDE, I noticed Port Master tray icon doesn't have a name in the tray, or in the tray settings

**Why do you and others need this?**: This is how it should be, the application should have a name not only an icon in the tray.

![Screenshot_20230220_002458](https://user-images.githubusercontent.com/17416415/219981765-9a95c19d-9019-459e-9522-0fae38f2d5c1.png)

![Screenshot_20230220_002437](https://user-images.githubusercontent.com/17416415/219981747-01ce3b0d-e7ee-4874-83df-0045b2148cdd.png)

**Comment by Raphty** [comment]
thanks for letting us know!

@dhaavi are you aware of this and is this in the backlog?

**Comment by Zorrototo** [comment]
Any feedback on the suggestion, to make it integrate better in Linux desktop? It doesn't break anything currently, besides you need to know what this icon is, or hover and wait for the popup.

**Comment by Raphty** [comment]
This got a bit lost in the last months, we will look into it. As you said, it is not critical and therefore not high on the list.

**Comment by dhaavi** [comment]
Hey @Zorrototo,

thanks for raising this with us.

The issue is that in the Linux ecosystem, things are very differently interpreted.
We had the title set previously, but removed it because Ubuntu displayed the full name in the try next to icon - which looked super weird and was a massive waste of space.

The relevant code is here:
https://github.com/safing/portmaster-ui/blob/cea7afe9ac5dbadc3bc3d1b5a14d218beb17b54e/notifier/tray.go#L64

We may revisit this in the future. I also sadly did not comment which Ubuntu version this was.
