### ISSUE TITLE
Softlocked Debian 11 on Kernel 6.0.0-0-amd64

### ISSUE THREAD

**Issue by tenesey** [safing/portmaster#1107]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
System: Plain vanilla Debian "Bullseye" (11) amd64 multiarch running backported kernel 6.0.0-0-amd64 on corebooted (actually, "Skulls" package) Lenovo Thinkpad x230. No DE, using Openbox as window manager. System has been my daily driver for the last three years and has been working fine.

Installed portmaster-installer-1.0.6.deb using gdebi. Worked for a few days without issue (other than blocking all internal communication between two guest VMs running on QEMU/KMS, but that was me not digging into the configuration yet). This morning, suddenly found some apps wouldn't start and the system was softlocked. Attempted a soft shutdown and got "BUG: soft lockup cpu#3 stuck for <time>" at the console which continued for several minutes. Hard-powered off; found that system would not boot using kernel 6.0 (three separate attempts). Externally booted system with "Sysrescue Disk", booted fine with that, internal file system checked out. Tried to restart under internal kernel 6.0 again, no go. Restarted under stock kernel 4.19.0-8-amd64 and system started correctly. Purged Portmaster & dependencies. Restarted under 6.0.0-0-amd64 (actually 6.0.12-1~bpo11+1) without Portmaster and the system booted as expected and now runs correctly.

I made no system changes since installing Portmaster. Removing Portmaster returned the system to its working state.

**What did you expect to happen?**:

The system to continue to boot and run correctly.

**How did you reproduce it?**:

See above.

**Debug Information**:

Unfortunately, this the best I can do. I'm not a developer, just a nerd who's been using Debian as a daily driver for the past 12 years. This laptop is my main system, so I don't have the ability to do debugging as I need it to get other things done.

**Comment by Raphty** [comment]
thanks for the report, and I fully understand your situation - I probably had similar experiences back in the day when I was messing around with my only Android phone - It happen on multiple occasion that I stayed up till the sun came up to get my phone back to work... 

Can you tell me did you do some other system update prior to to this issue? I understand that it now works with Portmaster gone, but since it has been working before, and there was no Update in Portmaster I am confused to why Portmaster should be the culprit.

**Comment by tenesey** [comment]
Raphty:
There had been no updates or configuration changes to the system after installing Portmaster. It was literally the last thing I installed to the system before the problems began. This is the reason I purged it: I was walking backwards through what changes I could remember. I can't guarantee that was the cause of the problem, but I had never seen this kind of glitch before. I have not ruled out some kind of hardware issue (the thing is 11 years old) but I am posting from it now and it seems to be back to normal under kernel 6.0. I am in the process of setting up a new laptop (there is no such thing as coincidence) so I might be able to put Portmaster back on and try some debugging in a few days if I can get some direction on what to look for.

**Comment by Raphty** [comment]
thanks for the response,

I was just wondering, it happens that people write us emails or create issues claiming it was and had to be Portmaster, and 2 days later, well apparently it was a system update and now everything works again... this is just a reality we have to live with.

If you can share more infos when it does not work in the future, pleas let us know, but since I cant see what we can do here, I will close this ticket.
