### ISSUE TITLE
DNS Leak: router logs have *.self-check.portmaster.home.arpa

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1137]
Not Related to Issue https://github.com/safing/portmaster/issues/1136
![image](https://user-images.githubusercontent.com/62152714/226189586-3dfb6b09-cd22-4ae6-a51c-e8d6bedb7ebc.png)

**Comment by dhaavi** [comment]
`*.self-check.portmaster.home.arpa` is used for an internal self-check of Portmaster. If you see these queries anywhere, the system integration is not working and you should get a notification about that in Portmaster after a while and you should really check your setup.

These queries cannot really leak anywhere by design, as they are only valid in the LAN context and MUST be discarded anywhere else per RFC.

**Comment by Rexadev** [comment]
> the system integration is not working 

What

>  you should get a notification about that in Portmaster after a while

No Notification

> you should really check your setup.

Setup ?

> These queries cannot really leak anywhere by design, as they are only valid in the LAN context and MUST be discarded anywhere else per RFC.

Where do you think is the problem ? WIndows ? Router ? DNS ?

**Comment by Kostrol** [comment]
> f you see these queries anywhere, the system integration is not working and you should get a notification about that in Portmaster after a while and you should really check your setup.

This isn't necessarily the case, no? maybe I'm misunderstanding. If you have something that logs all DNS traffic on your network, this will naturally and should be expected to show up. 

Could you elaborate?
