### ISSUE TITLE
An option to add an application as a favorite

### ISSUE THREAD

**Issue by Xcczs** [safing/portmaster#1196]
**What would you like to add or change?**:

As the title says, an option to add an application as a favorite would come in handy. Now there can be a lot of ways to implement this. One is to let us create a folder of applications in the "All apps" tab and another is, a button on the sidebar above the network activity button called favorites that does pretty much the same thing; it has all your favorite apps in one place.

**Why do you and others need this?**:

It would make it much easier and faster for people who use a lot of applications occasionally and want to tweak or view what's going on in their favorite apps without trying to find it every single time they want to see something.

**Comment by cospking** [comment]
![image](https://github.com/safing/portmaster/assets/108274310/a0a1d345-c350-4f34-bede-89cd989c586e)
Perhaps these red spaces could be used to show the icons of favorites apps, whether they're active or not so you can easily change settings before you start them.

For example I have some apps that require internet activity before launching to work at all or simply to carry out updates, but turn them off afterwards.

One example is Stable Diffusion, I tend to let it update but turn off internet access afterwards because I have no idea what certain extensions might do in the background without me knowing. Obviously I could use the offline toggle within the webui-user.bat but then I'd have to constantly add/remove that toggle.

**Comment by Raphty** [comment]
cool idea, we have been thinking about multiple Portmaster profiles, and we would most likely go down that rout to allow multiple changes at once (eventually with triggers to change automatically as well)
