### ISSUE TITLE
[Question] Do all Internet IPs have country ? Can there be any that don't ?

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1215]
Or the database is for "as much as possible" ?

**Comment by Raphty** [comment]
Great question, and sadly there is no easy answer.

You will have to split the answer from the start as well since there are[ two versions of IP in use v4 and v6](https://en.wikipedia.org/wiki/IP_address#IP_versions). V6 is different because we have a lot more of them and each device has a unique one and if that device travels the ip address travels with it...

we are much more limited in ipv4. In general there are geolocations associated with them - but you can buy an address and assign it in a different country as well.
[Wikipedia: Internet geolocation](https://en.wikipedia.org/wiki/Internet_geolocation)

For Portmaster we compile and update the geoloaction database every 1-3 months and each Portmaster install has a local copy of that data! is it always 100% up to date - no.
But things don't change that rapidly and for the typical person this is not a big threat.

**Comment by Rexadev** [comment]
> V6 is different because we have a lot more of them and each device has a unique one and if that device travels the ip address travels with it...

If you ignore the MAC Address part in IPv6

> For Portmaster we compile and update the geoloaction database every 1-3 months and

How ?

> each Portmaster install has a local copy of that data! is it always 100% up to date - no.

You should create a separate repo for it too

> But things don't change that rapidly and for the typical person this is not a big threat.

People don't expect a security software to be laxed
