### ISSUE TITLE
uBlockOrigin filterlist integration to portmaster bigtech

### ISSUE THREAD

**Issue by Morasithil** [safing/portmaster#1251]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**
What does the safing team think about adding ublockorigin's filterlist to the portmaster?
It could be an additional option next to the bigtech options.
Google/Youtube is restricting users from viewing videos when they use an addblocker like ublockorigin.
Using an adblock in 2023 is mandatory for privacy and security, as the internet becomes more sh!t than ever.
Youtube detects the adblockers and punishes the users, so i tought just integrate this to portmaster?
Invidious is a great options to get rid of youtube-google spying when watching news, but they might not be there forever.

**What did not work?**

**Debug Information**:

**Comment by Raphty** [comment]
Thanks for the suggestion!
**In general regarding filter lists**, we have to evaluate lists not just on their content but also on their license and if we are even allowed to use the specific list.
uBlocks list would be possible if I remember correctly, but when we looked into their filter lists, the issue was that the focus is different, their list is focused on urls and we have to be narrower at the moment and look at domains.

when we go for a browser integration we might revisit their list as well.

In general the basis for their list should have big overlaps where possible.

If you want to check if there is stuff missing in our lists pleas go ahead, the repo for our lists is: https://github.com/safing/intel-data
