### ISSUE TITLE
Add "Force Block Internet Access" Shortcut to Dashboard

### ISSUE THREAD

**Issue by avoidthehack** [safing/portmaster#1304]
+ Also change the Shield text to say "Secure - Internet access is being blocked" when Force Block Internet Access is enabled.

**What would you like to add or change?**:
I think adding a quick toggle to the dashboard for force blocking internet connections (alongside the quick links to the Privacy filter + DNS Service) could be beneficial for users. Also, knowing when it is enabled (via the Shield area) could be helpful... especially if it is enabled by accident.

**Why do you and others need this?**:
Since the dashboard is meant to be an overview, this is a good "overview" status. Users may need to cut internet access really quickly for any number of reasons; it'd be easier to just bring up Portmaster and hit the shortcut to the toggle in the settings.

**Comment by dhaavi** [comment]
I like the idea of having a "panic button" to cut access and we actually had something like this in the past, but more complex and it was difficult to understand, so we deprecated it.

Adding important global settings to the dashboard is a really neat idea. I don't think we have thought about this yet - thanks!

I am not sure if just linking the "Force Block Internet Access" setting will result in the correct expectations of the users, because the global setting is just the default and this can be overridden per-app. So if I push this "panic button" on the dashboard, this is only works for the apps where I haven't changed that setting.

If the use case is really a "panic button", then we should treat this differently - not as a setting, but as a special state of whole of Portmaster.
If it is meant for quickly changing the global defaults, and we are successful in communicating that correctly, I think this can also be very beneficial.

Can you elaborate on possible use cases you see and how you would expect this to work?

**Comment by avoidthehack** [comment]
I was trying to keep it simple because the Privacy Filter and the Secure DNS only linked to the Global settings, but since you brought it up, let's definitely explore the Panic button idea... I would need a little time to think on it though.

Off the top of my head... perhaps it would be have basic configuration profiles users could pick from. An easy/permissive state, the current defaults more or less, and then the hardcore "Panic" mode? Could you (or anyone else on the team) let me know thoughts on this?

If not the panic button (or "profiles"), I think perhaps including the toggle for "Force Block Internet Access" *and* some kind of indication it is enabled would be important as it is a pretty significant global setting. Personally, I've accidentally enabled it before, forgot to disable, and wondered what was wrong, heh.

Users may also need to kill internet connections globally if they're only trying to give access to a single app for access. Or perhaps there is suspicious traffic leaving a system. Or perhaps we want very fine control over the system's connections, so we default to globally denying app connections and then specifying which can connect to the internet.

**Comment by avoidthehack** [comment]
Revisiting this after giving it some thought.

IMO, I think the profiles would be the way to go - though I'm not sure how much work this would be for the team... but here we go!

When first onboarding, users can be invited with any overlay similar to the tips present in Portmaster now to pick a state/profile: Easy/permissive, "Balanced" (the current defaults are pretty good, tbh), and "Restricted."

These profiles could also be available in the Dashboard.

An Easy/permissive profile could be:
- DNS servers set to something that only blocks malware, such as Quad9 or Cloudflare (ideally Quad9).
- All connections permitted
- For filter lists, only use the MAL list

The Balanced could just be the default settings Portmaster comes with currently, as I think they are a good balance overall. 

The Restricted profile could be the settings in Balanced plus:
- Force Block P2P Connections set to yes
- Force Block LAN set to yes
- Filter lists enabled: TRAC, MAL, BAD, DECEP
- Force block internet connections set to yes (with the caveat apps allowed internet access override this)
- Use Secure Protocols Only set to yes
- Ignore System/Network servers set to yes (rolling with the assumption the current network isn't to be trusted)

**Comment by Raphty** [comment]
Thank you for the idea and the feedback! super valuable
starting with example profiles to help learn what they can do
