### ISSUE TITLE
Add "Recent Connections (Per App)" to Dashboard

### ISSUE THREAD

**Issue by avoidthehack** [safing/portmaster#1305]
**What would you like to add or change?**:
Add recent connections (maybe within last 30 min as a default?) initiated by apps

"RECENT APP CONNECTIONS

-List Top 3 Apps with the most connections in 30 mins-"

**Why do you and others need this?**:
This would be helpful "system overview" information the dashboard is meant to provide. I think it's important to know which apps have been recently initiating connections at a first glance.

**Comment by dhaavi** [comment]
Hey @avoidthehack, thanks for this suggestion!

The dashboard features "RECENTLY BLOCKED APPLICATIONS", because we think that people will often open the UI because something does not work correctly, so this is a shortcut there.

In order to get a good overview of active applications, this is what the overview in the side dash is for - you can now even sort that by most connections:
![image](https://github.com/safing/portmaster/assets/18184155/0d3e177d-9477-4dca-9fdd-07ff2578766f)

Can you elaborate on how this information in the dashboard would improve user experience? What is the exact use case for this?
Not trying to be snarky here - just trying to better understand. There might be a good and valid use case I cannot think of right now.

**Comment by avoidthehack** [comment]
Hey, thanks for the quick reply!

I assumed the dashboard would be fullscreen on a first launch (or as the default), so the side pane wouldn't be immediately visible without the additional click. On the [1.4 blog post](https://safing.io/blog/2023/08/21/portmaster-v1.4/), only the the fullscreen dashboard is showcased here, which IMO sets the expectation the dashboard would always come up like that unless you configure/click around.

For background, the side pane is always viewable for me (plus I know it's there + how to hide it) as I've been using Portmaster for a while - so I am thinking more of an onboarding / first time type lens here is all.

If this is indeed the case (as in, we are looking at it from a first start-up lense), I think it would be important to highlight the apps making the most connections on first sight. As a user, technical or advanced, I would definitely want to know of Edge is making 100+ connections (not an exaggeration, haha) right off the rip.

If not, then yes the side pane (or the default side pane + the dashboard) would suffice. :D

**Comment by Raphty** [comment]
In the blog I wanted to show the Dashboard better, this is why I cropped it like that 😅 

But the side pane is always visible when the screen size allows it.

**Comment by avoidthehack** [comment]
That certainly makes sense! In that case, I'm not opposed to closing this issue.
