### ISSUE TITLE
Recent Connections Countries - Greenland is larger than Canada?!

### ISSUE THREAD

**Issue by Morasithil** [safing/portmaster#1317]
**What would you like to add or change?**:
First of all thank you portmaster-team for creating a visual interface or if you want so GUI that makes it easy for anyone to see to which and how many countries our devices connect to, being able to see the normaly invisible might make it easier for many people to understand the importance of privacy.
I'm here to request a rework of the map you use, the size between countries is clearly highly incorrect.
For example on your map greenland is larger than canada which is obviously false.
According to the extremely biased website wikipedia:
Greenland: 2,166,086 km2 
Canada:     9,984,670 km2 

**Why do you and others need this?**:
I just think a map with accurate country size would be a great thing, might not be the nr1 on the priority-list but if would devinitely be great if you could rework the map at some point.

**Comment by Morasithil** [comment]
![false ratio](https://github.com/safing/portmaster/assets/136394696/a0968cfb-10b3-4986-904c-4cc3cc2c7e91)

**Comment by Morasithil** [comment]
![false ratio](https://github.com/safing/portmaster/assets/136394696/6eb766b1-f51f-4d9a-952b-1720faddb9f0)

**Comment by Raphty** [comment]
Hey @Morasithil thanks for the kind words.

The perceived size of countries is due to the map projection we use.

Any map will have some draw backs, and we opted to choose a "Cylindrical" style for the map, because they are easy to scroll through, and are nice rectangles. 

I think we could cut off a bit at the top and bottom.  
If you have an idea what map projection you would prefer we can look into it.

https://en.wikipedia.org/wiki/List_of_map_projections
