### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by mdksec** [safing/portmaster#1327]
Hello,

I hope you're doing well. I'm interested in helping translate the Portmaster project into different languages to make it more accessible to a wider audience. To facilitate this, I suggest setting up a dedicated CrowdIn page for Portmaster. CrowdIn is an ideal platform for collaborative translation work.

I'm keen to start contributing to the translation process and would appreciate your assistance in creating the CrowdIn page or initiating the translation work.

Thank you for considering my request. I look forward to your response.

**Comment by Raphty** [comment]
Thanks for the offer!

We have shied away from providing Portmaster in multiple languages because it is harder to develop new features when you have to do them in multiple languages.

We also have little experience in that regard. We hear the need, and we are thinking about it.

CrowdIn seems like a nice platform, thanks for the recommendation, if you have other options as well, we might be looking into them also.

We would start by looking into what our current databases would be compatible to first, and then decide.

thanks for the suggestion.
