### ISSUE TITLE
Starting Module interception failed 

### ISSUE THREAD

**Issue by livan3li** [safing/portmaster#1367]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues: 
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

1.First I've installed the application. After installation, I've opened the App and I've disabled all filters in first configuration window.
2. After some time, i removed the app and reinstalled back. And this time the app didnt ask me for configuraiton.
3. Now in dashboard it gives the error in the title.
4. and no application, no connection is being observed

**What did you expect to happen?**:
would open as usual and see the dashboard to observe trafic of device. 

**How did you reproduce it?**:
Even if i remove the app, i cannot fix the issue. So there is no way to reproduce it.   

**Debug Information**:
OS : Debian 12.2.0( not a Linux distro fork, Debian itself)

**Comment by Raphty** [comment]
of course knowing what the issue is before getting the debug info is always hard, but my guess is that during the deinstall iptables got removed and then not added during install.

To install `iptables` on Debian, you can use the package management system, `apt`. `iptables` is usually pre-installed on most Linux distributions, including Debian, but if it's not present or you need to reinstall it, here's how you can do it:

1. **Update Your Package List**: 
   Before installing new software, it's a good idea to update your package list to ensure you're getting the latest versions available. Open a terminal and run:
   ```
   sudo apt update
   ```

2. **Install `iptables`**:
   Now, install `iptables` by running:
   ```
   sudo apt install iptables
   ```

3. **Verify Installation**:
   After installation, you can verify that `iptables` is installed and check its version by running:
   ```
   iptables --version
   ```

**Comment by livan3li** [comment]
First of all, I couldnt get debug info. I've tried to copy as it's described when i was opening the issue but it didnt copy anything. 

After that I've done as you described, now it works fine. Thank you very much.
