### ISSUE TITLE
Stardew crash on entry to Willy’s shop

### ISSUE THREAD

**Issue by Chicken-Fingies** [safing/portmaster#1381]
**What happened**:
Stardew crashes upon entry to Willy’s shop about 50% of the time

**What did you expect to happen?**:
I expect to enter the room

**How did you reproduce it?**:
Enter Willy’s shop

**Comment by Raphty** [comment]
are you talking about this shop? https://stardewvalleywiki.com/Fish_Shop

I am sorry, but I cant see how Portmaster can be responsible for this.

If you truly think it is Portmaster, pleas send in the debug info while issue occurs.

**Comment by ErnieBall** [comment]
I have encountered this issue aswell, the game crashes when i enter the Fish Shop.
The issue is recreatable aswell, every time i try it happens.

I will attach, the log.txt from ports/stardewvalley
[log.txt](https://github.com/safing/portmaster/files/14284410/log.txt)

I'm not sure if there is further debuginfo i can provide. Following the link above "collect Debug info" the steps mentioned don't seem applicable for my device. (there is no /opt/safing/ ) But please let me know if i can provide more usefull data

For some context, i am using an R36S with ArkOS 2.0 (01272024-1),
Portmaster 8.7.1 with Mono 6.12.0.122

**Comment by alexbainter** [comment]
@Raphty Maybe you figured this out by now, but just letting you know this was probably meant for https://github.com/christianhaitian/PortMaster as Stardew Valley is one of their supported games. I'm not involved with that project, but this issue is ranking highly on Google for "Stardew Valley portmaster"-related queries (which is how I ended up here!)

**Comment by Raphty** [comment]
thanks!!

no did not look into that

closing the issue

**Comment by iqraut** [comment]
> **What happened**: Stardew crashes upon entering Willy’s shop about 50% of the time
> 
> **What did you expect to happen?**: I expect to enter the room
> 
> **How did you reproduce it?**: Enter Willy’s shop

Since it only happens about half the time, this sounds more like an intermittent loading or transition issue than a permanently broken save. I’d try entering the shop several times on a clean vanilla setup and note whether the crash depends on time of day, weather, or Willy’s location. If it still happens, a crash log from immediately after the failure would be especially useful for debugging. This [[Stardew Valley guide](https://stardewvalleyapk.app/)]can also help with general shop and location references.
