### ISSUE TITLE
Simplify export/import entire config

### ISSUE THREAD

**Issue by redactedscribe** [safing/portmaster#1382]
**What would you like to add or change?**:

One button to export the entire Portmaster config to make it a simple and quick process.

**Why do you and others need this?**:

With the 1.6.1 release (appreciated!), support to export profiles was added, as well as for the global settings, however it doesn't appear to be trivial to be able to export the entire configuration (i.e. both at once). Maybe I'm missing something?

The related release blog post says "next time your windows needs a reinstall or you want to try another linux distro you can easily take your Configurations from one Portmaster to the other." but this arguably isn't true, unless "easy" equates to meaning having to go through every single profile and creating a backup for each one.

It should be simple to backup the entire configuration (all profiles and the global settings). Additionally, if only wanting to back up the global settings, an "All" button would be useful instead of needing to check each checkbox before exporting. If this were the case, it should of course be as simple to import as well.

Thanks.

**Comment by dhaavi** [comment]
Hey @redactedscribe,

Thanks for this idea!

We are actually already working on something superior: With Portmaster v1.7, you will be able to synchronize all your settings with a directory on your system. You can then sync this directory with your other devices using your favourite tool or service.

Please note however, that we classify this is a convenience feature and thus will only be available in Portmaster Plus in order to support the ongoing development.

**Comment by redactedscribe** [comment]
That does sound convenient indeed. However it is a shame such a basic feature found in the majority of software will require a subscription. I personally would rely upon your strengths rather than typical marketing gotchas to try and get users to flip into paid customers. Thanks anyway.
