### ISSUE TITLE
Feature Request: Context Menu Entries

### ISSUE THREAD

**Issue by FADEC44** [safing/portmaster#1390]
**What would you like to add or change?**:

- Right-click/context menu shortcuts for convenience and improved UX. 

**Why do you and others need this?**:

- One example: blocking program connection before the first run.  Currently need to open Portmaster and manually create an app profile if it has never before been run.  It would be great to right click an installer, for example, and select "block all connections".  Portmaster would then create the app profile, and set its Default Network Action to "Block".

**Comment by Raphty** [comment]
Thank you for the suggestion, we might revisit this in the future!

as you have seen, we don't have a right click menu at the moment.

We are hesitant to implement one because it can be an "easy" shortcut and can therefore lead to bad design in the future, where the learning curve is even steeper then it already is.
