### ISSUE TITLE
Freeze Portmaster: Show connections only up to freeze moment when clicking apps/profiles/activity

### ISSUE THREAD

**Issue by redactedscribe** [safing/portmaster#1397]
**What would you like to add or change? / Why do you and others need this?**::

Each time you click an app/profile or the network activity for example, Portmaster refreshes and shows the latest connections. Normally this is useful, but when it comes to debugging a network related event it's inconvenient as you keep having to chase further and further down the lists each time you switch between apps/profiles etc as new connections keep being logged.

I'd like to be able to freeze Portmaster's logging/history on-the-fly so they'd only show the connections up to the moment of being frozen. Even if an app/profile hasn't been clicked (i.e. refreshed), when frozen the app/profile would show the state of the connections at that time. The freeze button would be readily available, e.g. listed within the spanner and screwdriver button so that it can be quickly enabled.

Portmaster would probably still continue operating as normal under-the-hood as this change would only be a UI/UX change, so when unfrozen, the connections would update to whatever has been happening during the freeze.

You have limited non-paying Portmaster users to only 10 minutes of logs/history. Ideally freezing would let us freeze this 10 minute window rather than the frozen connections being hidden once they reach 10m in age.

With this feature, it should be much easier to diagnose and fix certain types of network issues, like drop outs.

I hope this makes sense, thanks.

**Comment by Raphty** [comment]
thanks for the suggestion, it absolutely makes sense, the fun thing is, most people did not like when we opted to not auto refresh constantly and you ask for the 100% opposite 😅, but I get what you want.

because this is a niche request (most people I have heard want auto refresh everything... this of course can change)  
I can give you some hints how I go about this.

One major tip, if you don't yet know, when you hold `ctl` you can click to copy, and so get the information you need fast into a document or something


[Screencast from 2023-12-22 08-45-24.webm](https://github.com/safing/portmaster/assets/11504285/ad82cc40-ef31-42c4-b2c9-d25ee0d516c7)
you cant see the mouse... but you see what I am clicking.

I hope this helped

**Comment by redactedscribe** [comment]
Thank you for your reply.

I too am in favour of things auto refreshing, it just seems like the ability to pause that from happening is missing. Thank you for the tip about Ctrl, I have actually been using this already, however it really isn't enough for the situation I describe.

My use case: A VPN keeps losing connection seemingly at random. I want to check the connections for certain processes but each time I switch between the profiles I'm seeing new data which causes me to have to scroll down further to try and locate the moment of the VPN's disconnect. I would look at the Network Activity page but it's often full of System DNS Client spam which I'm not sure how to filter out (if even possible).

Some kind of pause/freeze would really help I think. Thanks for considering this FR.
