### ISSUE TITLE
v0.2.6 not compatible with windows 7

### ISSUE THREAD

**Issue by Happygolucky254** [safing/portmaster#1401]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
 Nothing Found.

**What worked?**
Manually going to C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app\portmaster-app_v0-2-5 and launching previous version. 

**What did not work?**

v0.2.6 ... I started using postmaster by installing v0.2.5 from version 1.6.2 on the website maybe 2-3 months ago. It pushed an update recently but the update never launches or starts the core service or application. For a while I thought it was being blocked by Comodo because it launched from a unique GUID path to execute.bat file that is automatically contained as unrecognized. However when I unblocked and launched still nothing would happen, no app, no core start, no ui. 

**Debug Information**:

Manually launching C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app\portmaster-app_v0-2-6\portmaster-app_v0-2-6.exe as nothing else works return the error. 

The procedure entry point 'DiscardVirtualMemory' was not found in the DLL 'KERNEL32.dll'

I already know this is a feature only supported in window 10 and up because of programming implementations.

Two Issues really. I don't know why you would remove support for older windows given its a cross-platform application so the programming should not really be dependent on Windows 10 functions. If you decided to removed compatibility, there was no reason to push an non working update. I can launch 0.2.5 manually along with the core but I'm not sure how well this is operating given the mixed versions and multi stream applications for each process, core, ui, app, kernel extension etc ...

Maybe it is a bug that is not intended, idk. All your documentation that I see is still saying window 7 to 11 for getting started guide.

**Comment by Raphty** [comment]
Hey there, thanks for reaching out, as you may or may not know, windows 7 is EOL for some time now. You are correct that Portmaster at its core should keep on working on w7 for some time now, but because w7 is not a platform apparently any of our beta testers is using, we were not aware that with this electron update windows 7 support dies as well.

The update was important for most other platforms though so we will not role it back, but for those who want to stay on w7 here is a workaround that can work: #1384 

We also currently are testing an electron replacement, but as mentioned w7 has been EOL for almost 4 years now and more and more software will stop working, I recommend looking into alternatives.
(Chromium already jumped ship, and Firefox will do so in next year)

**Comment by Gaming-tech-cyber** [comment]
well can't we just patch-in a electron compatibility layer?

**Comment by Raphty** [comment]
Sure, please follow the contribution guideline here: https://wiki.safing.io/en/Contribute#contribute-to-the-code
