### ISSUE TITLE
Installation: RPM: Installation doesn't finish

### ISSUE THREAD

**Issue by esdnm** [safing/portmaster#1413]
pressing crtl-C after a long period of time, it says, 
```
portmaster: Downloading portmaster modules. This may take a while ...

KeyboardInterrupt: Terminated.
```

I don't think it is a good idea that it does this during installation. This should be done after installation and during first run or during later running as user want.

(I lost a large part of my data package due to this)

**Comment by Raphty** [comment]
I am sorry for your experience, this seems to be an isolated incident though, and I have not seen any other reports about this recently. We do see periods where all our update servers are under heavy load because we get so many simultaneous installations, so this might have been a time based issue.

Again I am sorry for your Inconvenience.

**Comment by esdnm** [comment]
Does it download things during installation or not? If it does, i highly think it's a wrong decision.
