### ISSUE TITLE
"A Javascript error occurred in the main process" On Gui open

### ISSUE THREAD

**Issue by tuyuribr** [safing/portmaster#1423]
**What happened**:
When openning the GUI. it gives this error:

![err](https://github.com/safing/portmaster/assets/45042245/37f4caf1-cdb4-408b-bb22-e313a571f8eb)

**Debug Information**:

[debug info.txt](https://github.com/safing/portmaster/files/13992181/debug.info.txt)

No relevant logs were found

**Comment by IamVendetta** [comment]
I Have the EXACT Same ERROR Happening Right now.

**Comment by tuyuribr** [comment]
Still active in `Windows 10 Enterprise` and `v1-6-5`

**Comment by tuyuribr** [comment]
I found a "hack" to stop the error message.

First install 7-zip and the ASAR extension ( I'm using this one: `https://www.tc4shell.com/en/7zip/asar/` )
Then unpack the `C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app\portmaster-app_v0-2-8\resources\app.asar` 
Edit the index.js, put this `process.on('uncaughtException', function (err) {})`  before the `var electron_1 = require("electron");` line.
I put in line 38 rn.

Make a backup of app.asar, delete app.asar then zip again the folder in asar.

Or if you trust a lot in other people ( I doubt since you are using this program ), you can use my app.asar  :
[app.zip](https://github.com/safing/portmaster/files/14624656/app.zip)


Run portmaster.

**Comment by tuyuribr** [comment]
Only gives error in Windows enterprise

**Comment by Raphty** [comment]
the issue is does not impact Portmasters operation. It appears for some people when they pin Portmaster to their taskbar and open it through that.

We are fixing this in the new UI back-end.

In the meantime you can either ignore the error message, or open  Portmaster via the start menu or the tray icon.

If someone wants to help fix this in the electron version of Portmaster you are welcome to contribute, let me know in that case I can reopen the issue as well.

**Comment by TurtleIs** [comment]
I've been getting tis error, and is preventing any farther progress 
![awakened trade](https://github.com/safing/portmaster/assets/173210850/28dfc098-d0e9-46e3-9db6-0a489545c4f6)

what can I do to fix this?

**Comment by Raphty** [comment]
click ok and it should go away

it only happens when you open portmaster from an on the taskbar pinned icon
you can just open it from the start menu, we are fixing this with the new UI engine

**Comment by TurtleIs** [comment]
I did click "ok" and the error went away, but the program does not start up.... 
Isaac V. Counterman 

    On Tuesday, July 9, 2024 at 02:19:58 AM EDT, Raphael Fiedler ***@***.***> wrote:  
 
 


click ok and it should go away

it only happens when you open portmaster from an on the taskbar pinned icon
you can just open it from the start menu, we are fixing this with the new UI engine

**Comment by jaspi72** [comment]
Open services, find postmaster, click ok from error notice, restart postmaster core service and voila on me at least ;)

Using latest win 11 pro.

**Comment by jaspi72** [comment]
In PopOS linux worked like charm in first time
