### ISSUE TITLE
Add a light theme

### ISSUE THREAD

**Issue by JOTSR** [safing/portmaster#1435]
**What would you like to add or change?**:

A light theme is good for readability during all day light hours. Classical toggle (dark/light/system).

**Why do you and others need this?**:

A dark theme is not good for eye saving if the environment is bright. To improve readability/accessibility and improve eye saving the best is to reduce the light contrast between the screen and the environment so a light theme would be a great improvement.

**Comment by p0358** [comment]
It really is needed for accessibility, I'd probably reinstall this if that was a thing. On new IPS monitor it's closer to be legible than cheap TN, but still not it. But really, I suggest for the developers to try out how the app looks like on a cheap TN monitor with bad contrast and colors, it ain't pretty...

**Comment by CAJElevado** [comment]
Another reason is those with certain health conditions. As someone with astigmatism, l experience halation, eye strain, and eventually severe headaches if I look at a dark GUI long enough. I've struggled with this since the MS-DOS days in the '90s. I can tolerate white text on grey or similar BG a bit better than on a darker BG, but I'd love to see a proper light mode on Portmaster, which I now consider a must-have

**Comment by zorgoban** [comment]
There is definitely an interest and as a Windows Developer myself I wonder: You have to actively put effort into ignoring Windows System Settings. So why invest that effort when it clearly stirs irritation? You wouldn't even have to implement templates. Just stop ignoring color settings.
