### ISSUE TITLE
is incompatible with Windows API

### ISSUE THREAD

**Issue by 70V07** [safing/portmaster#1445]
is incompatible with Windows API wich provide (ad example) the default Enviroment Variables
_I learn this from an user... and now I have the proof is true, sadly... why I like this Portmaster_

if I use envs in File Explorer or Terminal like `%APPDATA%` doesent work

but if I shoutdown Portmaster all envs return operative and working

**Comment by Raphty** [comment]
not sure what you are doing, the file paths do work well in explorer directly.
![image](https://github.com/safing/portmaster/assets/11504285/5f6ca78b-d44d-44f7-bd38-4293c13aea77)

maybe someone else has a better idea, and can help

**Comment by 70V07** [comment]
I install Portmaster from scoop...

now I try to install it using the installer from official site

**Comment by 70V07** [comment]
ok Ive tried to install from official site instead scoop... all env variables work as expencted now :|

**Comment by Raphty** [comment]
great to hear! having Portmaster distributed in all those place is cool as people can find it more easily, but since it is not us doing it, you can never know what it is you are actually downloading there, and it might cause issues.

Keep in mind our installers are signed with an EV cert, so you can check if the installer you downloaded says Safing ICS Technologies GmbH
