### ISSUE TITLE
NextDNS support or do the same as they do for free =)

### ISSUE THREAD

**Issue by northys** [safing/portmaster#148]
**What would you like to be added**:

Currently I wasn't able to use NextDNS resolver together with Portmaster. I though it was because I haven't specified port (#147) but it doesn't work even with appending `:853`.

NextDNS over TLS works by providing unique subdomain to each user. e.g. iamnorthys.dns.nextdns.io. But when I try to set `dot://iamnorthys.dns.nextdns.io:853` it does nothing and fallbacks to resolvers specified by DHCP server.

**Why is this needed**:

It's not killer feature for me. It would be much better if you cold add stats similar to NextDNS.io + improve official blocklists (I think they use the same blocklists used by adblockers in browsers) or let users to load their own blocklists.

This is how NextDNS stats looks like. All I need is `Top resolved`, `Top blocked` and `Top root` domains + the list of queries DNS. I think it is not had to implement (it's just nice UI from some relational database and I suppose you don't collect those data locally now which is the hardest pard of this feature request IMHO) and customers will love it. It saves your customers another 3$ a month for nextdns or similar service and I'm willing to pay for it. I've stopped nextdns subscription just because you don't support it and I prefer portmaster over NextDNS ;)

![Screenshot from 2020-09-16 18-02-27](https://user-images.githubusercontent.com/2878126/93362888-d7320480-f846-11ea-9384-a6ce2eb83f62.png)
![image](https://user-images.githubusercontent.com/2878126/93362014-c92fb400-f845-11ea-80a5-0c907f2a7e2f.png)

**Comment by dhaavi** [comment]
> NextDNS over TLS works by providing unique subdomain to each user. e.g. iamnorthys.dns.nextdns.io. But when I try to set `dot://iamnorthys.dns.nextdns.io:853` it does nothing and fallbacks to resolvers specified by DHCP server.

As explained in the [DNS Servers guide](https://github.com/safing/portmaster/wiki/DNS-Server-Settings), we currently require an IP address. This is due to the chicken/egg problem of how to resolve that domain name without depending on any other resolvers, which may be disabled via configuration. It's not entirely clear to me how NextDNS has setup their infrastructure.
You could try it with `dot://45.90.28.0:853?verify=iamnorthys.dns.nextdns.io&name=NextDNS`.

> It's not killer feature for me. It would be much better if you cold add stats similar to NextDNS.io + improve official blocklists (I think they use the same blocklists used by adblockers in browsers) or let users to load their own blocklists.

Local connection history is a planned feature of the Portmaster. You can find it mentioned here: https://safing.io/backlog/
With it we will be able to provide statistics.

We have a simpler stats system planned that only works with live data for the near future. I will bring this up in the specification phase in order to check if we can maybe add some stats in this stage already, but without any persistence (restart resets).
 
> This is how NextDNS stats looks like. All I need is `Top resolved`, `Top blocked` and `Top root` domains + the list of queries DNS.

Thank you for this input, this will be very valuable when we get to implement that.

> I've stopped nextdns subscription just because you don't support it and I prefer portmaster over NextDNS ;)

Nice to hear that the Portmaster can bring you so much value in such an early stage! :D

I will close this issue, as there is no further action required here. Also, I will update the title to make it more friendly. ;)

**Comment by dhaavi** [comment]
One additional note regarding the DNS server settings. The current UI really _is_ MVP. The next version (_already in progress_) will be a lot more friendly in that regard.
