### ISSUE TITLE
Redesign Settings To Allow Detailed Rules

### ISSUE THREAD

**Issue by rbdevr** [safing/portmaster#1546]
Hello all,

I suggest to change the way Settings work. It is a big change but it will increase Settings flexibility drastically.
Allow the user to specify what to do in each scenario instead of having one "force block" option.
- Default Action
- Outgoing Local Machine 
- Outgoing LAN
- Outgoing Internet
- Incoming Access
- P2P Connection

And for each one the user can decide what to do:
- Default
- Allow
- Prompt Once
- Prompt Alway
- Block
- Force Block
- Block and Notify

I'm available if there are any questions.
Cheers

**Comment by Raphty** [comment]
We are thinking about gibber changes in the settings section, but we can't say when we will release them.

maybe some background for you (since you have so many great ideas!)

the reason we have the force block setting is because all settings are enforced top to bottom, so we have the force block settings so a (novice) user can quickly disable or enable functionality,

for more detailed settings you can always wirte the rules individually bellow. mixing prompt into this is something we have not thought about yet.
like I said in another issue, we are not big prompt users here, we like to configure the apps as we want them and then "forget" about them.

we currently don't have the resources to tackle these issues, but when we have them we will go back and look into the suggestions you provided. if you want to give more details please do.

also for chatting we are on discord, if you want to join us:   https://safing.io/discord

**Comment by rbdevr** [comment]
I want apps to be able to access local, always prompt me for LAN access and block internet access.
It would be great to have a more sophisticated settings to be able to handle all sorts of scenarios.
And also include one more action. notify. you block the access but you add a windows notification that the block occurred. so its like a prompt with automatic user no response and a windows notification.
I have added  in the original post.

**Comment by Raphty** [comment]
you can Archive your desired outcome now.

set the app to prompt and add two rules

- allow: Localhost
- block: Internet

![image](https://github.com/safing/portmaster/assets/11504285/82f3269e-d707-4526-9e85-6bcb43c3a480)

**Comment by rbdevr** [comment]
great thank you.
