### ISSUE TITLE
ISSUE - Portmaster seems to be limiting my download speed

### ISSUE THREAD

**Issue by ThijsTheMan** [safing/portmaster#1591]
**Checklist**:

 I'm using the official portmaster release (i.e no custom builds)
 I searched for similar/existing issues first.
 My issue is not mentioned in the Known Issues section of my [OS](https://docs.safing.io/)

**What happened**:

Today I tried to download a WeTransfer file but the download is going extremely slow. I have Gigabit internet around 900 MB/s (tested with speedtest.net) but it only shows around 2 MBp/s in anything I try downloading even installing or updating games through Steam or Epic Games. I tried following a different GitHub user's issue [https://github.com/safing/portmaster/issues/161?new_signup=true](url) but I just couldn't follow it or how they fixed it...

**What did you expect to happen?**:

Nothing =)

**How did you reproduce it?**:

Brave Browser + Portmaster + WeTransfer + SSD (with enough space) + Tested good internet connection (+- 1000 MBp/s)

**Debug Information**:

General Issue Debug Info: [https://pastebin.com/pSpj6KRf](url)

**Comment by vlabo** [comment]
Thank you for the report and for using portmaster.
We will try to reproduce and inactivate the issue for that we need a bit more info.

Are you using SPN while downloading?
If you shutdown Portmaster compliantly does the download speed go to the expected value?

**Comment by ThijsTheMan** [comment]
My SPN Module is disabled on this device, When I shutdown Portmaster the issue still persists. The issue started since I  had Portmaster. Thanks for responding

**Comment by vlabo** [comment]
Not sure if Portmaster can be the cause.
If Portmaster is not running it should not have any affect on the system since it is design in a way that does not change any OS configuration and the device will function as if it was not installed.

If the problem persists when portmaster is not running the cause is probably somewhere else.

**Comment by Gilles45398** [comment]
Hi

I've been lurking on Github for years and decided to create an account just to give my input on this bug. I ran into the same issue as @ThijsTheMan (sadly, I got no solution).

Once I've installed Portmaster (free install, no SPN used), I saw my download speed divided by 25. Disabling Portmaster won't solve the issue, even after a restart (Win 10 22h2), BUT uninstalling it does. It sadden me because I really like the software (I moved from Glasswire). I really hope for a workaround in the future.

PS - Just a thought @ThijsTheMan : may be killing the Portmaster Core can resolve it (not tested, I've already uninstall the software).

**Comment by dhaavi** [comment]
Hey @Gilles45398, thanks for taking the effort to report this.

If there is a speed reduction with Portmaster (but not without), the only thing that can cause this, is our kernel driver.
@vlabo just rewrote this part in Rust, and we are testing it in the beta release channel, in case you want to check it out. 

Here is how to get into beta: https://wiki.safing.io/en/FAQ/SwitchReleaseChannel

**Comment by Gilles45398** [comment]
> Hey @Gilles45398, thanks for taking the effort to report this.
> 
> If there is a speed reduction with Portmaster (but not without), the only thing that can cause this, is our kernel driver. @vlabo just rewrote this part in Rust, and we are testing it in the beta release channel, in case you want to check it out.
> 
> Here is how to get into beta: https://wiki.safing.io/en/FAQ/SwitchReleaseChannel

Hi,

Sorry for wenting MIA, had some IRL issues. Will test & report back. Thanks.

**Comment by Gilles45398** [comment]
After several days of test, everything went smooth, even in stable version. The issue is gone.

**Comment by Raphty** [comment]
thank you for the update

**Comment by julienth37** [comment]
Hi
Same issue here, 8 Gbps Internet, only 800 Mbps with Portmaster running, 1.4 Gbps with it closed (and service stoped). To cross-check I've opened a ticket at my ISP (I have about 5 Gbps upload and only 1.4 Gbps download, very strange).

**Comment by PacksInHiding** [comment]
Ive experienced that same issue twice over the past years, with the only change being having Portmaster installed or not.
Issue persists with, no idea why.
