### ISSUE TITLE
Tailscale Incompatibility

### ISSUE THREAD

**Issue by alexk101** [safing/portmaster#1658]
**System Info**
Distro: EndeavourOS
CPU: 8-core AMD Ryzen 7 6800H with Radeon Graphics (-MT MCP-)
speed/min/max: 503/400/4785 MHz 
Kernel: 6.10.5-arch1-1 x86_64

**What worked?**
Still able to ping 1.1.1.1 and access the internet through IP's directly

**What did not work?**
When using Tailscale with portmaster, I am unable to resolve any DNS queries.

**Debug Information**:

NJ{"Created":1723998797,"Modified":1723998797,"Expires":1726590797,"Deleted":0}S
executing core/portmaster-core version 1.6.10 on linux amd64
240818 12:33:17.254 ▶ BOF
240818 12:33:17.386 entication:291 ▶ WARN 001 api: denying api access from 127.0.0.1:45742
240818 12:33:18.387 entication:291 ▶ WARN 003 api: denying api access from 127.0.0.1:58746
240818 12:33:19.388 entication:291 ▶ WARN 005 api: denying api access from 127.0.0.1:58762
240818 12:33:20.390 entication:291 ▶ WARN 007 api: denying api access from 127.0.0.1:58768
240818 12:33:21.391 entication:291 ▶ WARN 009 api: denying api access from 127.0.0.1:58776
240818 12:33:22.392 entication:291 ▶ WARN 011 api: denying api access from 127.0.0.1:58790
240818 12:33:23.146 les/worker:109 ▶ ERRO 013 resolver: service-worker ip info delayed cache writer failed (1): could not start database cache (type bbolt): timeout - restarting in 2s
240818 12:33:48.321 pat/module:112 ▶ ERRO 015 compat: self-check #3: dns integration check failed: failed to receive test response: lookup a81429592840200e3b8934c09b3931629b.self-check.portmaster.home.arpa. on 100.100.100.100:53: read udp 100.96.67.87:50287->100.100.100.100:53: i/o timeout
240818 12:33:57.736 e/core/api:118 ▶ WARN 017 core: user requested shutdown via action
240818 12:33:57.837 dules/stop:057 ▶ WARN 019 modules: starting shutdown...
240818 12:34:00.326 ◀ EOF

**Comment by alexk101** [comment]
I have discovered a work around. Tailscale manually overwrite `/etc/resolv.conf` to do dns resolution when it is unable to correctly interface with `systemd-resolved`. This is the default behavior on most distros bundled with `NetworkManager` & `systemd-resolved`. To allow Tailscale to properly communicate, follow the instructions [here](https://tailscale.com/kb/1188/linux-dns)

**Comment by CommanderTurtle** [comment]
> Unresolved issues should remain open so people actually look at them, these aren't discord threads

Very true. And half the problem with the development community. Bot is a massochist, and portmaster has no busy development these days. Repo probably needs more contributors and maintanance.

<img width="2247" height="595" alt="Image" src="https://github.com/user-attachments/assets/c5758880-4db7-4815-8287-ec5ed69dee35" />

but obviously jokes aside. The wiki is self-maintained and supposedly receiving more ease-of-edits by the community. But hopefully more to come on that front. Likewise, I think we need to give them credit for being smaller of a team than we might think. There aren't many contributors to an entire vpn stack (open source) like this one that's multiplatform, and it's up to us as the community to attempt to put in work here. I mean, if you're a coder who likes convoluted networking processes, a maintainer of a lib or something for qubes or kvm, I'm sure they'll happily take any PRs thrown their way. 

Community doesn't develop so much since this winds up being more of a consumer-faced product, even though the ones who use it are always Privacy caring people, they're still 98% non-technical people, due to the nature of the marketing. I'll see once I get more agents spun up if I can do any help myself, but it honestly it does look like this much. At least the ivpn merger has people hopeful for the direction of the project/company. So there's more good to say than there is bad.
