### ISSUE TITLE
Closing program and uninstalling it - after this I have issues with connection

### ISSUE THREAD

**Issue by stnufc** [safing/portmaster#268]
Hi! Firstly, sorry that English isnt my native language. I tried to write simple, but its hard when my PC isn't set on English (so I had to google some windows terms - I had **Windows 10**)
 
 I'm installed your program on Friday, but had hard time understanding some settings. Anyway when I tried to turn it off in settings, there was a message '**Connecting to portmaster service** (or server? dont remember)' and it lasted for many minutes, so I closed program in task manager. I killed all processes there and tried to launch program again, but couldn't - there was just a **blank white page**. Program could have launched again after windows restart, but I couldn't turn it off. So **I uninstalled it.**

 But now I have consequences. I noticed some troubles with my connection, some sites won't open ('The requested URL was rejected. Please consult with your administrator.') and also when I open 'network connections' in windows, I'm clicking on my lan connection - and it not showing me for how long I use this connection and not showing my activity (bytes) - I never ever seen this before - its just blank where the numbers should be. It resolves and showing info ([like here for example](https://blink.ucsd.edu/_images/technology-tab/network/Local%20Area%20Connection-1.png)) if I disable and enable this connection again.
 
 Any steps I can do to fully uninstall / clear consequences of installing? I tried flushing dns (I do that sometimes anyway), also tried some ipconfig cmd like netsh winsock reset catalog and etc. 
 
 Now (before publishing) I even tried and reset my whole net settings in Windows 10 by using 'Network reset', but it didnt helped me :(((( 
 
 I thought about windows restore points, but I only had 1 that was saved week ago, so I dont want to do that... But can you say, could it solve my problem? Will Windows Restore Points bring my settings back (of course if my problem roots are lies here in the 1st place)? Any other ideas how to solve my troubles? Should I install program back?

**Comment by davegson** [comment]
Hey there, sorry to hear you encountered these issues. I am not the technical expert, but on Monday @dhaavi, our lead dev, will be online and likely be able to help more.

Until then, you can [view the installation details on our docs](https://docs.safing.io/portmaster/install/windows#installation-details), which describes what the Portmaster does on installation. The uninstaller should cleanly revert all these steps - can you check manually if these steps were correctly reverted? If not this might be causing the errors.

**Comment by stnufc** [comment]
Thanks! I should have read more before installing it. I already used similar program that showed me what URLs some windows programs are trying to connect to, so I thought it will be fine. I still don't know, what if its just a coincidence (but I never had these troubles before and I'm wary of installing any programs on my new laptop)? Although its strange that when I tried to disable portmaster in program itself, it really just gave me message about 'connecting to server', while nothing happened... 

I checked that installation path to program was fully uninstalled. Right now, error **'The requested URL was rejected. Please consult with your administrator'** is not happening anymore - don't know what helped or caused it. But strange that after rebooting PC Windows still not showing me numbers of duration, speed & activity [like that](https://blink.ucsd.edu/_images/technology-tab/network/Local%20Area%20Connection-1.png) (its always showed me before - I change DNS settings sometimes, so I see it often). Only after I disable and enable it showing me these numbers. 

Still not sure if its fixed or not... Can Windows Defender interfere with program? Just dont know...

> In order to gain the required system integration for the Portmaster to function properly, the Installer needs to deactivate the system’s DNS Cache Service - the Portmaster replaces this service. This may break/impair some other software that depends on special functionality of said service. This is done by setting the registry key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache -> Start to 4 and rebooting.

Can this be problem? Although I checked in services.msc - dns client is run and have autolaunch... Is there may have any other services that I should check (that can conflict with portmaster)?

**Comment by dhaavi** [comment]
Hey @stnufc,

The Portmaster tries to leave your system alone as much as possible. The only big change we sadly need to do in order to be able to fully integrate is that we need to disable the `dnscache` / `DNS-Client` Windows service. This normally does not have any effect on other software, but in some edge cases it does.

It could be that your other program depends on said service and therefore does not operate normally.

When you uninstall the Portmaster, it reverts everything it did during install. Please note that you absolutely __must__ reboot after uninstalling in order to get the `DNS-Client` Windows service to run again.

This might have been the source of your troubles.

---

> Although I checked in services.msc - dns client is run and have autolaunch...

Great!

---

> Is there may have any other services that I should check (that can conflict with portmaster)?

There is no other service that the Portmaster makes changes to. Also, we don't know of any other Windows services that interferes with the Portmaster, although we cannot rule that out.

---

> PC Windows still not showing me numbers of duration, speed & activity

I don't know why Windows would stop showing statistics in the network interface window. That seems weird. Could it be that your other software uses a virtual network device and your traffic is being counted there instead?

---

We are still working on the User Experience of the Portmaster, so some things may not work as expected. What happens when you stop the Portmaster via its UI is that it actually stops the Portmaster Core Service and therefore the UI cannot connect to it anymore and not load anything from it, resulting in a white window. We are working on improving that.

Take a look at the architecture diagram on this doc page, it might help you understand: https://docs.safing.io/portmaster/architecture/overview

**Comment by LostinSpacetime** [comment]
I did install Portmaster on Linux (Ubuntu 20.10) and did encounter some Problems with websites not loading. I deinstalled it (purged) and now Firefox and Epiphany cannot reach any websites. I installed a Chromium snap and everything works as intended. Can someone please tell me what the Portmaster changes on a linux system?

**Comment by dhaavi** [comment]
Hey @LostinSpacetime,

the Portmaster does not change any configuration on Linux. It just adds some iptables rules at runtime in order to gain the required control of network traffic.
All of these rules are both removed by the Portmaster when it stops _and_ by the systemd service when it is stopped.

Should something not have happened here, because it was not stopped cleanly, you can always remove the added chains by __rebooting__ or __like this__:
```
sudo /sbin/iptables -F C17
sudo /sbin/iptables -t mangle -F C170
sudo /sbin/iptables -t mangle -F C171
sudo /sbin/ip6tables -F C17
sudo /sbin/ip6tables -t mangle -F C170
sudo /sbin/ip6tables -t mangle -F C171
```

**Comment by LostinSpacetime** [comment]
@dhaavi Thank You for your answer. It helped. I found the problem elsewhere.

**Comment by dhaavi** [comment]
The issues mentioned here seem to resolved. Please feel free to comment and reopen is that is not the case.
