### ISSUE TITLE
Proposal: report full blocklist name instead of ID in response's TXT debug info

### ISSUE THREAD

**Issue by northys** [safing/portmaster#273]
**What would you like to be added**:

Change
blocked: example.com. in activated lists LIST_ID
To
blocked: example.com. in activated lists LIST_FULL_NAME

**Why is this needed**:

Because I see full blocklist name in Portmaster Dashboard so it's hard to find it by the 3 letter ID. All those IDs looks the same when you are trying to find it in the collapsed tree.

**Comment by dhaavi** [comment]
Thanks for bringing this up. The current solution is temporary until we figure how to go about this at best.
Changing the wording on the reason is a simpler change we could do even sooner.

Do you think just using the full list name is enough? Shouldn't we also add the category the list is in?
Examples:
- `[Analytics] Disconnect.me Tracking Domains`
- `Disconnect.me Tracking Domains (Analytics)`
- `Disconnect.me Tracking Domains (Ads & Trackers -> Analytics)`
- `Disconnect.me Tracking Domains [DM-TR] (Ads & Trackers -> Analytics)`
- `Disconnect.me Tracking Domains (DM-TR in Analytics)` (my current fav)

What happens when something is blocked by 5 (or more!) lists? Things would clearly get out of hand.

This is not so easy. 😉 And I welcome your feedback and thoughts on this.

**Comment by northys** [comment]
I love this one: `Disconnect.me Tracking Domains [DM-TR] (Ads & Trackers -> Analytics)`

> What happens when something is blocked by 5 (or more!) lists? Things would clearly get out of hand.

I expect that portmaster goes through the list and waits for first block so each query will be blocked by different list until there is no block. So I'll get angry and block all 5 one by one untill there is nothing to block my query.

**Comment by northys** [comment]
Why is BYX show under Experiments category in my portmaster while I see the BYX (https://github.com/safing/intel-data/blob/bdf8e01588ec13c25c31203c9ab2642df13b2569/lists/sources.yml#L476) in ADS category? It's confusing. How does it work? Do I have outdated intel-data?

**Comment by davegson** [comment]
on the master branch it is categorized in EXPERTIMENTS:
https://github.com/safing/intel-data/blob/master/lists/sources.yml#L483

Somehow you landed on a wrong branch/commit

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
