### ISSUE TITLE
ProtonVPN on Linux works

### ISSUE THREAD

**Issue by davegson** [safing/portmaster#320]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**

works perfectly as reported via matrix

**Comment by JacksonBarker** [comment]
I am not able to open Proton VPN on Linux if "Block Bypassing" is enabled for Python because Proton VPN attempts to use its own secure DNS resolver.

**Comment by AntiWorkIncel** [comment]
It's not compatible because Portmaster won't let ProtonVPN use it's own DNS providers.
Since the current ProtonVPN Linux app is just a graphical interface to manage OpenVPN, you need to edit OpenVPN profile to allow it to use it's own secure DNS and remove all the DNS servers from Portmaster list, and then you'll be using ProtonVPN DNS, but when you turn the VPN off, you'll need to put your DNS servers in Portmaster manually again.
This and this tutorial https://wiki.safing.io/en/FAQ/MakeSoftwareCompatibleWithPortmaster is what worked for me, although I'm not 100% sure, it just worked.
You guys should update the compatilibity page and say that ProtonVPN requires workaround.
