### ISSUE TITLE
Tor integration

### ISSUE THREAD

**Issue by Emmmmanuel** [safing/portmaster#321]
Hello!
I know the main goal of Portmaster is the future integration of SPN. But I think it would be interesting, as an alternative (in particular for those who can't afford this service) to be able to connect freely through Tor. 

I think that, since Tor will be a lot slower it will still encourage people to pay for the SPN.

It would also be great to be able to specify wich app or services will be redirected through Tor.

**Comment by dhaavi** [comment]
Hey @Emmmmanuel,

thanks for this interesting suggestion. You are right to assume that this is a very strategic question. I will not be giving an official statement here, but want to share some thoughts and insights:

From a technical perspective, creating this integration would be loads of work. We would need to rebuild big parts of the Tor software and keep it maintained in order to have a clean and stable integration. Currently we do not have the resources to do that. We would also not gain anything from it, monetarily speaking.

So our focus remains SPN: We charge for the SPN not to become rich, but to make a living and pay our bills. Only by having this business model can we continue to do this full-time and extend the team to continue to develop and maintain our services.

There might be different approaches to push down SPN prices in the long-term, and we will evaluate this as the time comes, since we want to offer more people access to the SPN. One possibility might be to offer our technology to businesses and with the resulting revenue then push down prices for customers.

But all of this is rather far away, so as of today it is not yet clear where we'll end up, but one thing is certain: We are dedicated to the privacy of our users and we will continuously find new ways to offer better privacy to more people.

**Comment by dhaavi** [comment]
Thank you for encouraging words. We too are very excited for what is to come!

I'm closing this to keep the issue tracker clean - if you have any other questions, feel free to ask!
