### ISSUE TITLE
Use standardized build system for cross-platform source building

### ISSUE THREAD

**Issue by xero-lib** [safing/portmaster#337]
**What would you like to add or change?**:
Add a makefile for building packages/installing software

**Why do you and others need this?**:
QOL

**Comment by xero-lib** [comment]
Also, submitting a package to the AUR would probably be really beneficial.

**Comment by ppacher** [comment]
> A makefile can be used for cross compilation by reading environment variables at runtime, and choosing what to do from there.

So it should automatically compile for the current platform? I'm not sure what you mean exactly because that's what go  (and pretty much all compilers) already do. 

> I would hope the makefile would be able to check for normalized dependencies, and install go/npm deps where possible.

While that would be possible there's no standard/normalized way of doing that and we would need to use a lot of bash (or sh if bash is not available) scripting for a lot of different distributions and is likely to break with little changes to either our dependencies / required tooling or with the availability of upstream/distro packages. That's a lot of maintenance work that's easier solved by documenting the required dependencies/tooling and users (of likely unsupported distributions) that want to build it on their system just install the platform/distribution specific packages on their own.

> Also, submitting a package to the AUR would probably be really beneficial.

We already track a request for AUR in safing/portmaster-packaging#30. Until that is done, you can already use the PKGBUILD from the the [portmaster-packaging](https://github.com/safing/portmaster-packaging/blob/master/linux/PKGBUILD) repo. You can also have a look at the documentation for installing on arch/arch-based distros [here](https://docs.safing.io/portmaster/install/linux#arch-linux) if you'r not familiar with using PKGBUILDs directly.

**Comment by chovy** [comment]
I would also like to see an arch (aur) package....

**Comment by dhaavi** [comment]
Closing in favor of https://github.com/safing/portmaster-packaging/issues/30 - please reopen if another issue persists.
