### ISSUE TITLE
IMAP marked as Unidentified Processes

### ISSUE THREAD

**Issue by Celuni** [safing/portmaster#343]
Why are IMAP Port 993 (E-Mail) requests marked as "Unidentified Processes" instead of Thunderbird?

`accepted     192.168.x.x:x TCP>  x.x.x.x:993   to imap.gmail.com.       x:x:x-         P#-1 [M] allowed by rule: scope matches Internet - by filter/endpoints @ core:profiles/local/_unidentified`

Windows 10
Portmaster v0.6.16

**Comment by dhaavi** [comment]
Hey @Celuni,

Sometimes connections cannot be accurately attributed to a process, even Windows itself does not always provide that information in it's APIs.
This is nothing unique to TCP or IMAP, but affects all connections.

Does this happen with _every_ connection, or just here and there?

**Comment by Celuni** [comment]
So far I've only seen that with imap and dns requests.

**Comment by ppacher** [comment]
We do try to get the PID in the kernel callout but it isn't available most of the time since we're registered at a pretty low kernel level for packet inspection.

As you already mentioned, hooking is a very unstable technique and will likely cause additional and hard to debug issues. Moreover, hooking is something that's normally done by malware or otherwise malicious software so it's not something we consider for the Portmaster.

We just had a discussion on the process detection part in windows and might be able to improve it a bit but that detection is always a "best effort" and can fail. Though, I'll try to reproduce that with Thunderbird in the next days. Let's see :)

**Comment by dhaavi** [comment]
Hey @Celuni, we cleaning up old issues, does this still happen?
