### ISSUE TITLE
Wayland and KDE compatibility

### ISSUE THREAD

**Issue by trekjunky** [safing/portmaster#344]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**
Nothing

**What did not work?**
Couldn't start Portmaster error messages

**Debug Information**:

**Comment by ppacher** [comment]
Hi @trekjunky, thanks for reporting.

It would be great if you could provide a bit more debug information on your issue. What operating system are you using? Also, could you please attach the [log files](https://docs.safing.io/portmaster/install/linux#accessing-the-logs)? Without those information it's hard to tell what the actual issue is.
The UI is based on electron which has received native wayland support a few days back - it's not yet in our UI release but it should still work with xorg-server-xwayland. So Wayland should not make any issues here. Also, KDE is used to work with the notifier (and electron doesn't really care). The actual portmaster service does not use any UI frameworks at all so running on KDE/Wayland should not affect anything there. 
As mentioned above, please attach the log files and some more debug information so we can have a serious look at your issue.

**Comment by 8BallBomBom** [comment]
Been running KDE Plasma Desktop via x11 for a long while and now recently Wayland.
The Portmaster Notifier and App seem to be working all good on my end.
