### ISSUE TITLE
Manjaro DNS Resolution Fails With Hardcoded Server

### ISSUE THREAD

**Issue by IanJSaul** [safing/portmaster#358]
**What happened**:
Removed UFW and GUFW.
Installed Portmaster on Arch by following official documentation.
Restarted system.
Portmaster failed to update and "because filterlists not loaded" entries found in KSystemlog.
No ping to 1.1.1.1 no DNS resolution.

**What did you expect to happen?**:
Ping to 1.1.1.1 and DNS resolution.
Portmaster to download/update required elements as needed.

**How did you reproduce it?**:
I had hardcoded my local OPNsense firewall as the DNS provider for that NIC, by removing it, I can cause the issue to occur or resolve.
Portmaster now updates filterlists, and appears functional.

I've never reported a bug in Git before, I hope this is of assistance to others.

**Comment by ppacher** [comment]
Hi @IanJSaul,

thanks trying out and for reporting!

When you say you "hardcoded your local OPNSense firewall as the DNS provider for that NIC", do you mean you configured the DNS server in Portmaster or on your system (i.e. /etc/resolv.conf, ...)?

It would also be great if you could attach the debug information from the settings page.

**Comment by ppacher** [comment]
Hi @IanJSaul,
thanks for replying.

The Portmaster does not take DNS configurations into account as it comes with a default set of DNS servers that are considered [trust-worthy](https://safing.io/blog/2020/07/07/how-safing-selects-its-default-dns-providers/). If you want Portmaster to use your local OPNSense firewall you need to configure the DNS server in Portmaster itself. Since it works as a firewall all outgoing DNS requests are automatically redirected to Portmaster. There is no way for plain DNS queries to bypass Portmaster. 
If you set the [Portmaster DNS Server](https://docs.safing.io/portmaster/settings#dns/nameservers) setting everything should work as expected.

**Comment by IanJSaul** [comment]
Completely understood - and I'm fine with being able to update that setting/manage it within Portmaster.

Since I think it's a somewhat common occurrence to have coded DNS into a network connection, I more-so wanted to post this to help others, or have Portmaster perhaps "detect" that this was potentially the issue, and display a warning condition.
