### ISSUE TITLE
Recommend a system restart after installation.

### ISSUE THREAD

**Issue by styromaniac** [safing/portmaster#369]
PortMaster slowed my computer down before I did a system restart, which resolved the slowness. Also, bugs begin to show after a system restart. See https://github.com/safing/portmaster/issues/368 . People need to see the bugs immediately crop up, IMO.

I forgot to mention that closing the UI before first system restart caused PortMaster service to stop. This isn't a problem after a system restart.

**Comment by ppacher** [comment]
Hey @styromaniac ,

thanks for reporting that. A system restart should not have any effect on a linux installation. Everything should be as it would be after an reboot (except you did a portmaster-upgrade). The high CPU usage might be the result of the Portmaster downloading and processing filterlist updates. This takes a bit of a time after the initial installation. While that processing is running, the Portmaster should show a "Filterlist update in progress" (don't know the exact wording right now) notification. Do you know if that notification was available when you experienced the system slowness?
Regarding the bug - as mentioned above - a system restart should not do anything different so that should have appeared without the restart anyway.

> People need to see the bugs immediately crop up, IMO.

That's somewhat hard to achieve because that normally depends on the type, kind and conditions required to trigger a bug ;)

> I forgot to mention that closing the UI before first system restart caused PortMaster service to stop. 

Not sure how this could have happened. Could you please fill out the issue template and provide the debug data / logs? The issue template is really important as without that data it's hard to tell anything ...
