### ISSUE TITLE
Is Mac OS support in the future implied by your website?

### ISSUE THREAD

**Issue by styromaniac** [safing/portmaster#370]
I see "MACOS (NOT SUPPORTED)" with the Apple logo next to it, so I assume that means this will change in the future. The fact that you support Linux already means to me that you have some of the work for Unix kind of done already. I know that Mac OS and Linux are different operating systems, but there's some overlap between the two.

Is my assumption true?

**Comment by davegson** [comment]
Hey there,

yes, macOS is planned at some point in the future. Our focus lies elsewhere at the moment, but you can get an overview of the bigger things we want to tackle in the mid- to longterm [in the backlog](https://safing.io/backlog/).

In terms of macOS itself, we wrote some more info about our recent assessment, with a few question-marks in terms of Apple's long term strategy with "network extensions" as they are called on macOS.
https://docs.safing.io/portmaster/install/status/mac

We can happily continue discussing this in the closed thread, but closing since it is a question and not an issue
