### ISSUE TITLE
Whitelist Filter Lists

### ISSUE THREAD

**Issue by MaiAsagi** [safing/portmaster#393]
**What would you like to add or change?**:
A Filter List similar to the Filter List for bad domains.

The feature would just be a simple checklist similar to the aformentioned Filter List for bad domains.

**Why do you and others need this?**:
This would be useful in the rare chance that breakage does happen. I am aware that Portmaster has the best defaults for the least amount of site breakage but I think having a fallback would be useful.

**Comment by ppacher** [comment]
Hi @MaiAsagi,

thanks for reaching out to us!

This is already possible by using [Endpoint Rules](https://docs.safing.io/portmaster/settings#filter/endpoints). You can allow domains on a per-app or global level. Since those rules are checked before the filterlist you can use them as an allow-list for domains that would otherwise be blocked by the filterlist system.

Hope that helps :wink:
