### ISSUE TITLE
Brave connection fails when secure DNS with custom provider is enabled

### ISSUE THREAD

**Issue by Raiyan-AP** [safing/portmaster#418]
When I have portmaster enabled with any DNS configuration and use Brave with secure dns with your current service provider enabled, everything works fine. 

But setting Brave to use a custom provider, even the default ones, will result in any website giving the error:
DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE

I don't exactly get what or why this is happening and I tried whitelisting Brave in portmaster but that didn't help. The connection also only gets disabled after a while and not instantly. Every other app I use works fine.

**Comment by dhaavi** [comment]
Hey @Raiyan-AP, thanks for reporting this issue.

In order to handle this issue properly, please submit the debug information:
- Open the affected application
  - Reproduce the problem
- Open the Portmaster UI
  - Select the affected application on the Network Monitor page
  - Click the "Copy Debug Information" button to the right
- Paste the data into a new comment here
  - Switch to "Preview" mode
  - Check the "Network Connections" and "Unexpected Logs" sections for potential sensitive data
    - Other sections do not include potentially sensitive data

With this information we can provide better and more accurate support.

**Comment by dhaavi** [comment]
Thanks for the debug data. From a general perspective everything seems to be in order.
I suspect the Portmaster is blocking connections of Brave, specifically the DNS connection.
What is weird about the error message though, is that it says that DNS requests are possible (`DNS_PROBE_POSSIBLE`).

I could not find a matching (blocked) connection in debug data though - have you redacted it?

When my assumption is correct, the following is happening:
Brave tries to connect to a secure DNS provider, but the Portmaster blocks it, as this bypasses the Portmaster's privacy protection. The Portmaster itself handles DNS securely for your whole device, which means you don't need to use application level DNS protection. 

Here are two solutions:
- Option 1 (recommended): Disable "Use secure DNS" in the Brave settings. Brave will then use the Portmaster for Secure DNS and everything should work.
- Option 2: Open the Portmaster UI, go to the App Settings for Brave and disable [Block Bypassing](https://docs.safing.io/portmaster/settings#filter/preventBypassing). This will let Brave use Secure DNS, but the Portmaster will see less of Brave's traffic and will be missing data to display and to effectively protect you when using Brave.

Please report back if one of these solutions worked for you.

**Comment by boistordu** [comment]
this problem is related to mine: 
https://github.com/safing/portmaster/issues/424
Why portmaster should be anywhere involved when put in a trusted zone? Why couldn't we disable the dns control of portmaster in trusted zone? Should not we be possible to be able to do that? I would imagine that in trusted zone you would like maybe to test a connection with another dns server to see if maybe it's  a problem of dns server, or diagnose all sort of network problem... Why then the dns protection of portmaster should be enabled at that point ?

**Comment by dhaavi** [comment]
> this problem is related to mine: #424 Why portmaster should be anywhere involved when put in a trusted zone? Why couldn't we disable the dns control of portmaster in trusted zone? Should not we be possible to be able to do that? I would imagine that in trusted zone you would like maybe to test a connection with another dns server to see if maybe it's a problem of dns server, or diagnose all sort of network problem... Why then the dns protection of portmaster should be enabled at that point ?

Hey @boistordu, thanks for the pointer, we will respond in the other issue.

**Comment by Raiyan-AP** [comment]
This issue has been fixed. I don't know exactly when but I think it was during the new UI update.

Before, if an app used its own secure dns, Portmaster would block that connection (eg: turning on secure dns on chromium or network.trr.mode to 3 on firefox) and for some reason, you needed to disable block bypassing on both the individual app setting and the Portmaster global setting which severely limited Portmaster's functionality. 

Now the bug has been fixed and just turning off block bypassing for the individual app allows that app to connect properly. So you can use different dns resolvers for specific apps and Portmaster's dns for everything else. Great to see more stability improvements.
