### ISSUE TITLE
Process detection is too slow for high volumes of new connections

### ISSUE THREAD

**Issue by changemenemo** [safing/portmaster#420]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
Ubuntu 21.10

Using stremio or transmission
Postmaster took out the cpu completely 
Still not sure if it's the UI or the backprocess

Caused also the dashboard to not be able to connect to the process 

**What did you expect to happen?**:
It should not be a ressource hog especially when it was not on limited mode but in trusted mode. 

**How did you reproduce it?**:
Launch some torrents download software and see what happens after a few minutes 

This is not a vpn related issue since the vpn connection is handled by another device (pi4) and it's a small mobile setup. Laptop + tablet + Poe switch + 2 pi4 
Tablet is a y intel cpu so not beefy.
Laptop is a u intel cpu so not beefy either 
**Debug Information**:
Will come later

**Comment by boistordu** [comment]
![Screenshot from 2021-11-03 07-50-50](https://user-images.githubusercontent.com/9523075/140557170-5c2d992a-6028-4308-8c58-99549c981535.png)

here is an example that's why I let wip in the title because I don't have the time to do debugging at the time when I do the tickets since I'm doing it most of the time from my phone

**Comment by dhaavi** [comment]
Hey @boistordu, thanks for reporting this.

`htop` shows the core service using a lot of resouces. Please copy the debug information in the settings _while experiencing the issue_ and paste it here. We can then see what the Portmaster is currently doing and where the resources are going into.

**Comment by boistordu** [comment]
Okey you think you will have a good some more information in the debug logs ? Is there a command line to do this? Because the interface at that moment become unresponsive and I need to stop it with systemd ...
So you see my problem there to actually give you debug logs

**Comment by dhaavi** [comment]
You can open `http://127.0.0.1:817/api/v1/debug/core?style=github` in your browser. You can just paste the full thing here, it will format correctly.
Please be reminded to do this _while experiencing the issue_.

**Comment by boistordu** [comment]
So this is happening right now as we speak.
I m busy with work so I can't like do a gif to show you you different kind of terminals with htop, glances, and iotop. 
![image](https://user-images.githubusercontent.com/9523075/140957478-339c2d16-0646-4480-b302-5cb963dbd5db.png)

![image](https://user-images.githubusercontent.com/9523075/140957935-784b0f62-a25f-4aa1-a408-4e947d8b5108.png)

That's why I've asked you a cli debug tool not something relying on your node backend. Which is really bad and which you should drop ASAP. 
And I m sorry if I'm being rude guys, but i guess you can also imagine how frustrating it is to just not being able to not debug a thing because for convenience (which I can totally hear as a valid reason) the devs has been relying on node.js which has been like demonstrated as a pain in the ass and a blackhole as security. 

So what can I do now to debug your app without the help of this infamous debug tool?

**Comment by dhaavi** [comment]
Thanks for hanging in there and doing your best to get us the debug data.

> sorry if I'm being rude

I understand this can be frustrating, still I would like to remind you: you owe us nothing, if this becomes too much of a hassle or is interfering with your work or other important stuff, you are free to stop or even uninstall the Portmaster. 

> [your node backend] is really bad and which you should drop ASAP.
> the devs has been relying on node.js which has been like demonstrated as a pain in the ass and a blackhole as security.

Likewise, we do not owe you anything. I am giving you a warning that such a tone does not follow [our code of conduct](https://docs.safing.io/community/code-of-conduct). It is neither respectful nor productive.

In terms of developing a CLI tool, that is not done in a heartbeat. It would require weeks or months of effort and currently we have more pressing matters to tackle.

In terms of language, the Portmaster Core Service itself is written in Go and is quite performant.
The User Interface on the other hand, is built with Angular (which includes node.js) and is currently using Electron (which also includes node.js) as a platform. We know about the drawbacks of both, and we handle the Angular UI itself with great care in respect to security. [As documented](https://docs.safing.io/portmaster/architecture/user-interface#why-do-you-use-electron-for-the-user-interface), we have the long term plan to ditch Electron one day.
To reduce further confusion, please note that the Tray Notifier is technically a separate piece of software, which is also written in Go, in order to limit the time that Electron needs to be active.

Since the UI seems to cause a lot of issues on your end, you can enable the [Development Mode](https://docs.safing.io/portmaster/settings#core/devMode) and open the UI in your browser at <http://127.0.0.1:817/>, this might bring you a performance improvement.

In regards to getting the debug information - while rather raw - you can call the API in your terminal, in case you prefer:
`curl http://127.0.0.1:817/api/v1/debug/core?style=github`

We appreciate your efforts and are looking forward to continuing in a more respectful manner.

**Comment by boistordu** [comment]
So 
I totally understand your difficulties. And since I don't program in go I can't comment on that, I just know from my dev perspective in C++ java it's always easier to do a cli debug point of a process than using the interface. Point of view that I'm sure we share about the fact interface and backend must always be separate. 
But again I don't dev in go. 
So here is some other proof that your link to your backend through a browser doesnt work that well which renders the debug process when your process is running into a loop (which I suspect it does here -> cpu hog) impossible.
![Screenshot-20211016124744-1436x1342](https://user-images.githubusercontent.com/9523075/141743187-98d95a10-1a4d-47dd-9814-92cf3387e7d3.png)
 
the curl works when your process is not into a loop. When it is then the curl just simply timeout.

**Comment by boistordu** [comment]
by the way you still didn't confirm me or deny the fact if it would be useful to have debug logs after had to kill the process and restart it or not ? I do'nt know if your logs are persistent for example?

**Comment by dhaavi** [comment]
> backend through a browser doesnt work that well which renders the debug process when your process is running into a loop

Even with high CPU usage, delivering the interface should no problem at all - in the screenshot, the Portmaster responds within milliseconds.
The error you see in the screenshot is the Portmaster denying access to the interface via the Browser. I assume you forgot to enable the [Development Mode](https://docs.safing.io/portmaster/settings#core/devMode). You should only use the [Development Mode](https://docs.safing.io/portmaster/settings#core/devMode) for debugging.

> by the way you still didn't confirm me or deny the fact if it would be useful to have debug logs after had to kill the process and restart it or not ? I do'nt know if your logs are persistent for example?

The logs itself are persisted on disk and are kept for about a month.
The debug data I am requesting however, contains lots of runtime data that is fetched live from the internal system and is not persisted. Usually, the debug data is much more helpful than the logs.

**Comment by boistordu** [comment]
Ow sorry you meant that. I thought you meant the dev tools. 
And portmaster might respond in milliseconds but then the rest of the system doesn't follow and the interface clearly does not.

**Comment by boistordu** [comment]
your backend really doesn't like torrent.
your soft with 7.10 has gone haywire and put itself in insecure mode .
I've wanted to restart it with the interface itself, it was really painful but it did happen eventually so at least the interface was semi responsive. 
When portmaster is going haywire like that it goes something like that for the rest of the system:

```
boistordu@noone:~/Music$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=60 time=4197 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=60 time=3166 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=60 time=2143 ms
64 bytes from 1.1.1.1: icmp_seq=6 ttl=60 time=42.4 ms
64 bytes from 1.1.1.1: icmp_seq=7 ttl=60 time=54.2 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=60 time=4004 ms
64 bytes from 1.1.1.1: icmp_seq=8 ttl=60 time=69.7 ms
64 bytes from 1.1.1.1: icmp_seq=9 ttl=60 time=70.0 ms
64 bytes from 1.1.1.1: icmp_seq=10 ttl=60 time=58.6 ms
64 bytes from 1.1.1.1: icmp_seq=11 ttl=60 time=51.1 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=60 time=6594 ms
64 bytes from 1.1.1.1: icmp_seq=12 ttl=60 time=61.8 ms
64 bytes from 1.1.1.1: icmp_seq=13 ttl=60 time=46.0 ms
64 bytes from 1.1.1.1: icmp_seq=14 ttl=60 time=62.5 ms
64 bytes from 1.1.1.1: icmp_seq=15 ttl=60 time=64.9 ms
64 bytes from 1.1.1.1: icmp_seq=16 ttl=60 time=57.9 ms
64 bytes from 1.1.1.1: icmp_seq=17 ttl=60 time=61.4 ms
64 bytes from 1.1.1.1: icmp_seq=18 ttl=60 time=150 ms
64 bytes from 1.1.1.1: icmp_seq=19 ttl=60 time=224 ms
64 bytes from 1.1.1.1: icmp_seq=20 ttl=60 time=269 ms
^C
--- 1.1.1.1 ping statistics ---
20 packets transmitted, 20 received, 0% packet loss, time 19125ms
rtt min/avg/max/mdev = 42.369/1072.326/6594.157/1856.493 ms, pipe 7
boistordu@noone:~/Music$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=60 time=984 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=60 time=380 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=60 time=255 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=60 time=512 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=60 time=311 ms
64 bytes from 1.1.1.1: icmp_seq=6 ttl=60 time=432 ms
64 bytes from 1.1.1.1: icmp_seq=7 ttl=60 time=509 ms
64 bytes from 1.1.1.1: icmp_seq=8 ttl=60 time=476 ms
64 bytes from 1.1.1.1: icmp_seq=9 ttl=60 time=512 ms
64 bytes from 1.1.1.1: icmp_seq=10 ttl=60 time=399 ms
64 bytes from 1.1.1.1: icmp_seq=11 ttl=60 time=510 ms
64 bytes from 1.1.1.1: icmp_seq=12 ttl=60 time=596 ms
64 bytes from 1.1.1.1: icmp_seq=13 ttl=60 time=508 ms
64 bytes from 1.1.1.1: icmp_seq=14 ttl=60 time=531 ms
64 bytes from 1.1.1.1: icmp_seq=15 ttl=60 time=567 ms
64 bytes from 1.1.1.1: icmp_seq=16 ttl=60 time=432 ms
^C
--- 1.1.1.1 ping statistics ---
16 packets transmitted, 16 received, 0% packet loss, time 15016ms
rtt min/avg/max/mdev = 254.999/494.712/984.442/154.040 ms
```

[portmaster-debug-0.7.10-stremio.txt](https://github.com/safing/portmaster/files/7717463/portmaster-debug-0.7.10-stremio.txt)

**Comment by dhaavi** [comment]
It seems that the Portmaster is handling north of 2500 connections again _at the same time_. This just cripples it.

There is also still no indication why that happens. I'd like to take a step back and make sure we didn't miss anything obvious:
- Is the [Permanent Verdicts](https://docs.safing.io/portmaster/settings#filter/permanentVerdicts) setting enabled?
  - It is by default, so if you haven't change anything, it will be enabled.
- Are processes detected correctly?
  - Ie. not all connections are in the "Unidentified Processes" app.
- Do you use packet or connection marks anywhere in your firewall (iptables)?

Also, when it happens again, please:
- Open a terminal and run: `netstat -tupen` - Please save the output and just post the number of connections here for now.
- Disable [Process Detection](https://docs.safing.io/portmaster/settings#core/enableProcessDetection) and see what happens.

**Comment by boistordu** [comment]
> It seems that the Portmaster is handling north of 2500 connections again _at the same time_. This just cripples it.
> 
> There is also still no indication why that happens. I'd like to take a step back and make sure we didn't miss anything obvious:
> 
>     * Is the [Permanent Verdicts](https://docs.safing.io/portmaster/settings#filter/permanentVerdicts) setting enabled?
>       
>       * It is by default, so if you haven't change anything, it will be enabled.
> 
didn't change that. But of course in the world of p2p it would probably not have the biggest effect if it tries a lot of new connection to a lot of new peers to get the chunk of file needed.
>     * Are processes detected correctly?
>       
>       * Ie. not all connections are in the "Unidentified Processes" app.
> 
A lot of them are identified under the right section which would be transmission or stremio but a lot are not not too. But I need to re-run this test under your new version 0.8.4 to be sure.

>     * Do you use packet or connection marks anywhere in your firewall (iptables)?
> 
No definitely not, The processing power of this unit would be too little to handle that so I try to avoid those kind of rules in those kind of hosts. 
> 
> Also, when it happens again, please:
> 
>     * Open a terminal and run: `netstat -tupen` - Please save the output and just post the number of connections here for now.
> 
>     * Disable [Process Detection](https://docs.safing.io/portmaster/settings#core/enableProcessDetection) and see what happens.

Will try with the new version those last 2 diag protocol. But I can attest that 0.8.4 didn't improve much things, it sill needs 50% or more if available of the total amount of CPU.

**Comment by boistordu** [comment]
in the mean time that I organize myself to do the differents tests, I've done some screenshots since the version 0.8.4 did make a little improvement into classifying the connections. Now it's recognized under more or less the good section "Node" (which could be a bit more refined but that's fine). But I wanted to show you that indeed yes this kind of usecase do imply a variation of 100-150 connections. It's not that clear on a screenshot so I should probably do a gif to show you exactly but the amount of connections was going up and down very rapidly between 15900 and 16200 every 2 seconds something like that. It's of course depending of the amount of peers etc. The printscreens will give you some kind of an idea nevertheless.
![Screenshot at 2022-03-08 02-32-24](https://user-images.githubusercontent.com/9523075/157216197-99fadb7a-cf85-4b4e-96d6-64579eeef993.png)
![Screenshot at 2022-03-08 02-32-51](https://user-images.githubusercontent.com/9523075/157216203-8291710f-f485-4edd-91e4-72569e48c3eb.png)
![Screenshot at 2022-03-08 02-33-00](https://user-images.githubusercontent.com/9523075/157216210-a6b559ff-deb6-4d5c-a251-202c6d71faa8.png)
![Screenshot at 2022-03-08 02-33-11](https://user-images.githubusercontent.com/9523075/157216215-40c56479-ceff-405f-b6eb-724ba3dd8d2d.png)

**Comment by boistordu** [comment]
![stremio_connections_Peek 2022-03-08 13-12](https://user-images.githubusercontent.com/9523075/157236240-e6bc7a2a-614d-4fe8-b7f8-3a603b5e0292.gif)
sorry for the lack of fps but the cpu was already at 100 because mostly of portmaster processing so you can't see the variations in a more fluid way but that would give you some idea. 
The torrent was a small one, about 4 connections and a variations of 100 to 250 waiting list.

**Comment by boistordu** [comment]
and since I want to be as thorough as possible for you guys I4ve made the netstat watching for a couple of minutes.

[watch_netstat_stremio.txt.zip](https://github.com/safing/portmaster/files/8206056/watch_netstat_stremio.txt.zip)

**Comment by boistordu** [comment]
> Hey @boistordu, thanks for all the data.
> 
> 
> 
> That's definitely _a lot_ of connections. I can totally see how attributing all these connections to a process will take down a non-beefy machine.
> 
> 
> 
> The only real way to solve this is to make process detection _a lot_ faster. Currently, I don't see a way to do this, but I hope we can use the new eBPF system and get the PID of a connection directly from the kernel, instead of having to search `/proc`.
> 
> 
> 
> Until we get there, can you maybe reduce the amount of connections that stremio uses?
> 
> I found a guide in that direction: https://blog.stremio.com/modify-bittorrent-settings/
> 
> 

Good point. Let me think maybe also of an additional feature or a workaround that might help reduce the detection or reduce the need of approval of those connections maybe.

**Comment by dhaavi** [comment]
Ok, thanks! Looking forward to your ideas.

**Comment by Bananaman** [comment]
@dhaavi What if we do what OpenSnitch does?

https://github.com/evilsocket/opensnitch

https://github.com/evilsocket/opensnitch/wiki

They use eBPF to inject some code in the kernel which apparently is very fast at identifying processes?

https://github.com/evilsocket/opensnitch/wiki/monitor-method-ebpf

**Comment by Bananaman** [comment]
eBPF may also fix misidentification:

https://github.com/safing/portmaster/issues/747

**Comment by Bananaman** [comment]
Whatever is causing this bug, it finally affected me too on Portmaster 1.0 and 1.0.2.

`portmaster-core` would constantly go into a 100% CPU usage mode which was so sever that the computer could barely even wake from standby (taking about 5 minutes for the screen to turn back on because `portmaster-core` was deadlocking everything somehow).

So I finally had to uninstall Portmaster and went back to the default `firewalld` instead.

This happened on both Fedora 36 and Fedora 37, fully updated systems in both cases.

Here's my **/opt/safing/portmaster/config.json:**

```json
{
  "core": {
    "expertiseLevel": "expert",
    "log": {
      "level": "warning"
    }
  },
  "filter": {
    "blockInbound": 6,
    "endpoints": [
      "+ 192.81.241.171"
    ],
    "lists": [],
    "serviceEndpoints": [
      "+ Localhost",
      "+ LAN ICMP",
      "+ LAN udp/5353",
      "+ LAN udp/5355",
      "+ LAN udp/1900",
      "+ LAN udp/546",
      "+ LAN udp/137",
      "+ LAN udp/138",
      "+ LAN tcp/22",
      "+ LAN */3389",
      "+ * */1025-65535",
      "+ 192.168.122.0/24",
      "- *"
    ]
  }
}
```

There was a `logs` subfolder of that location, and the `core` folder had some logs which all contained an error about updating via Electron which may be related:

```
[33m221130 23:01:21.298 v/location:299 ▶ WARN 001[0m netenv: failed to get IPv4 device location from traceroute: failed to send icmp packet: write ip4 0.0.0.0->1.1.1.1: sendto: operation not permitted
[31m221130 23:01:23.416 r/electron:050 ▶ ERRO 003[0m Failed to set SUID permissions for chrome-sandbox. This is required for Linux kernel versions that do not have unprivileged user namespaces (CONFIG_USER_NS_UNPRIVILEGED) enabled. If you're running and up-to-date distribution kernel you can likely ignore this warning. If you encounter issue starting the user interface please either update your kernel or set the SUID bit (mode 040000755) on /opt/safing/portmaster/updates/linux_amd64/app/portmaster-app_v0-2-5/chrome-sandbox
[33m221130 23:01:23.416 s/upgrader:074 ▶ WARN 005[0m updates: failed to handle electron upgrade: failed to chmod: chmod /opt/safing/portmaster/updates/linux_amd64/app/portmaster-app_v0-2-5/chrome-sandbox: operation not permitted
[33m221130 23:01:43.762 on/nfq/nfq:209 ▶ WARN 007[0m nfqueue: no verdict set for packet pkt:3 qid:17140 (192.168.122.250 -> 192.168.122.1) after 20.000566342s, dropping
[33m221130 23:01:44.322 on/nfq/nfq:209 ▶ WARN 009[0m nfqueue: no verdict set for packet pkt:11 qid:17040 (192.168.122.1 -> 192.168.122.250) after 20.001066771s, dropping
[33m221130 23:01:46.924 on/nfq/nfq:209 ▶ WARN 011[0m nfqueue: no verdict set for packet pkt:15 qid:17140 (192.168.122.250 -> 192.168.122.1) after 20.000494243s, dropping
[33m221130 23:01:46.924 on/nfq/nfq:209 ▶ WARN 013[0m nfqueue: no verdict set for packet pkt:16 qid:17140 (192.168.122.250 -> 192.168.122.1) after 20.000409123s, dropping
[33m221130 23:01:46.924 on/nfq/nfq:209 ▶ WARN 015[0m nfqueue: no verdict set for packet pkt:14 qid:17140 (192.168.122.250 -> 192.168.122.1) after 20.000622733s, dropping
[33m221130 23:01:49.584 r/core/api:115 ▶ WARN 017[0m core: user requested shutdown via action
[33m221130 23:01:49.685 dules/stop:057 ▶ WARN 019[0m modules: starting shutdown...
```

Either way I have uninstalled it now because Portmaster made my computer unusable.
