### ISSUE TITLE
End blocked connections immediately rather than timing them out

### ISSUE THREAD

**Issue by theusaf** [safing/portmaster#430]
**What would you like to add or change?**:
When blocking a connection, the connection being blocked should be immediately ended, rather than left to time out.
Or at least an option to have either behavior or per-app/domain, etc.

**Why do you and others need this?**:
Currently, when opening certain apps and web pages, if they make a connection to a blocked domain and have to wait for the request to pass or fail before loading other stuff, it can pause the load speeds of said apps and websites for several seconds.

**Comment by theusaf** [comment]
OS: Windows 10

Some example websites affected:
- https://docs.microsoft.com/en-us/windows/release-health/release-information
- https://www.geeksforgeeks.org/linked-list-set-1-introduction/
- Also affects apps like the Minecraft Launcher

Filter lists enabled:
- TRAC, MAL, PHISH, FRAUD, BAD

**Comment by Aziks0** [comment]
Same issue, also on W10.

The chrome web store takes about 20sec to load, but the worst is [this website](https://www.ecranlarge.com) that takes a whole 1min30 to load (it takes 1sec to load on my phone, so it's not a server issue). I basically can't use the site on my PC anymore, because I have to wait every time I open an article.

TRAC, MAL, BAD and WSP from EXPERIMENTS are enabled.

**Comment by northys** [comment]
Anyone experience that on Linux? Cause for me its Windows only issue.

**Comment by cridus** [comment]
Man. The very reason I installed this software was to block connections from specific countries. Turns out they don't get blocked and just get timed out.  
In my use case, it's like not having Portmaster at all, because sessions don't last long and so connections don't reach the timeout duration.  
Can you guys do this change, please? Even as a developer mode-only option or something, if you don't want to make it the default. Your program would be perfect if it would close connections, I doubt there's another one with the same features that does it.  
Please end my suffering 😭

**Comment by cridus** [comment]
By the way, I looked at the code of the kernel extension and it seems like it should indeed send ICMP packets to drop UDP "connections".
In the `pm_kext/src/pm_callouts.c` file, at line 172 it does `sendBlockPacket` when the verdict is "block", then in that method in the `pm_kext/src/pm_packet.c` file, at line 499 it calls `sendICMPBlockedPacket`. Is that not supposed to end that connection?  
Also what's the difference between the "block" verdict and the "drop" one? Why does the latter not call `sendBlockPacket`? Could it be that it's actually the one used when connections only get timed out?  
Please help me understand.  
  
Here's the two files I referenced, for convenience:
https://github.com/safing/portmaster-windows-kext/blob/develop/pm_kext/src/pm_callouts.c
https://github.com/safing/portmaster-windows-kext/blob/develop/pm_kext/src/pm_packet.c

**Comment by cridus** [comment]
By the way, I looked at the code of the kernel extension and it seems like it should indeed send ICMP packets to drop UDP "connections".
In the `pm_kext/src/pm_callouts.c` file, at line 172 it does `sendBlockPacket` when the verdict is "block", then in that method in the `pm_kext/src/pm_packet.c` file, at line 499 it calls `sendICMPBlockedPacket`. Is that not supposed to end that connection?  
Also what's the difference between the "block" verdict and the "drop" one? Why does the latter not call `sendBlockPacket`? Could it be that it's actually the one used when connections only get timed out?  
Please help me understand.  
  
Here's the two files I referenced, for convenience:
https://github.com/safing/portmaster-windows-kext/blob/develop/pm_kext/src/pm_callouts.c
https://github.com/safing/portmaster-windows-kext/blob/develop/pm_kext/src/pm_packet.c

**Comment by otherside1** [comment]
Has this been fixed

**Comment by cridus** [comment]
Anyone? At least almost 6 months later?  
Can I at least get a reply to my post above?

**Comment by dhaavi** [comment]
Connections are actively blocked by the kernel extension using ICMP and TCP RESET.
We implemented that end of 2022.

"Drop" is a silent block, where there is no active response, packets just disappear.
