### ISSUE TITLE
Compatibility with casting

### ISSUE THREAD

**Issue by boistordu** [safing/portmaster#433]
**What would you like to add or change?**:
I've added the other day to deactivate it for hein able to cast to a chrome cast and I guess it would be the same for a tv or other things. 

**Why do you and others need this?**:

It was in trusted mode and I l not sure why port master would block it since it is initiated first by a broadcast coming from the host itself but I will check it with wireguard first

**Comment by boistordu** [comment]
Well if I have any which can come up over time yes, but for the moment I don't have any idea to actually give it more unless a video. 
But it's not because something is in wip that in the mean time you can't just act upon it.

**Comment by davegson** [comment]
Hey @boistordu,

after re-checking all of your issues I realized what you mean with the `(wip)`. After an issue is closed you replace the `(wip)` with `(resolved)`.

I now understand where our mis-communication happened. "Work In Progress", or "WIP", is often used among developers to communicate that something is **not done** yet and still needs work _before_ action can be taken. That is the reason we were hesitant to respond.

After understanding our mis-understanding we will now handle them just as any other issue. 

I will also remove the `(wip)` from all active titles to avoid confusion for future readers. GitHub already manages the issue's state with "open/closed" so that extra steps is not really necessary for the future. I will also mark all messages about the confusion as off-topic

Thanks again for testing the Portmaster, for all your reports and efforts!
Have a good one 😄

**Comment by boistordu** [comment]
Well I'm still waiting on how you would like me to debug this. Obviously you won't see anything in the log since I had to stopped portmaster to have casting to work. 
Unless you are telling me otherwise? So should I what? Make a video then?

**Comment by dhaavi** [comment]
Hey @boistordu,

Which application are you using to cast to chomecast? How this normally works, is that the application will use multicast to find the chromecast, which we don't yet fully support.

As a workaround, you can add a "Allow `LAN`" to the [Incoming Rules](https://docs.safing.io/portmaster/settings#filter/serviceEndpoints) of that application.

**Comment by boistordu** [comment]
It was Google chrome in that case. I wanted to do it the most compatibilty one. 
So I was using the casting option on Google chrome under Ubuntu

**Comment by dhaavi** [comment]
Were you able to get it to work with the workaround?

**Comment by boistordu** [comment]
Will update it as soon as I tried again
