### ISSUE TITLE
Rules Timing Out

### ISSUE THREAD

**Issue by thegranddesign** [safing/portmaster#439]
**What happened**:

After allowing or denying a connection, the rule disappears after a given period of time.

**What did you expect to happen?**:

The rule should remain.

**How did you reproduce it?**:

Open an app, it attempts to phone home, I deny the request, I close the app, I reopen the app, it attempts to phone home, I get another prompt.

**Comment by dhaavi** [comment]
Hey @thegranddesign, thanks for reporting this.

We are seeing this or similar behavior now and then but were unable to exactly pinpoint this. We are tracking this in #391.

In order to keep everything in one place, I am closing this as a duplicate in favor of #391, please continue the discussion there.
