### ISSUE TITLE
The installer needs to install ffmpeg correctly

### ISSUE THREAD

**Issue by ata-star** [safing/portmaster#490]
[control] 2022/01/06 12:39:08 starting /opt/safing/portmaster/updates/linux_amd64/app/portmaster-app_v0-2-2/portmaster-app_v0-2-2 --data /opt/safing/portmaster
/opt/safing/portmaster/updates/linux_amd64/app/portmaster-app_v0-2-2/portmaster-app_v0-2-2: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory
[control] 2022/01/06 12:39:08 app/portmaster-app.zip failed with: unknown exit code exit status 127
[control] 2022/01/06 12:39:10 starting /opt/safing/portmaster/updates/linux_amd64/app/portmaster-app_v0-2-2/portmaster-app_v0-2-2 --data /opt/safing/portmaster
/opt/safing/portmaster/updates/linux_amd64/app/portmaster-app_v0-2-2/portmaster-app_v0-2-2: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory
[control] 2022/01/06 12:39:10 app/portmaster-app.zip failed with: unknown exit code exit status 127
^C[control] 2022/01/06 12:39:14 got interrupt signal, exiting... (not executing anything)

#electroniscrap

**Comment by davegson** [comment]
Closing due to overlooking the templates and the venting vibe.

As mentioned in https://github.com/safing/portmaster-ui/issues/196 you are welcome to participate within the terms of our [Code of Conduct](https://docs.safing.io/community/code-of-conduct)

If others experience this issue too, please create a new bug report
