### ISSUE TITLE
Portmaster disables Firefox's DOH

### ISSUE THREAD

**Issue by GeorgeCyriac** [safing/portmaster#500]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
[❌] [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
[❌] [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
[❌] [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
I use Firefox as my everyday browser and I have **[Adguard DNS](https://adguard-dns.com/en/welcome.html)** set up on it. Since I installed Portmaster, Firefox queries have been going through **Dot** instead of the **Doh** I set it to. I did some digging and found out that it makes Firefox fall back to plain DNS. I understand why Portmaster does this, but I already have **uBlock** installed on Firefox which gives me control over the domains, ads and trackers to block, which I think is sufficient. In this case, Portmaster becomes redundant. (I prefer **Doh** over **Dot** for my browser)
I tried troubleshooting and I '**think**' I found out that Portmaster creates a _user.js_ file, which turned out to be empty. Deleting it made no change. I tried **about:config** and it showed that **[network.trr.mode](https://wiki.mozilla.org/Trusted_Recursive_Resolver)**, which is responsible for the falling back of DNS in case **TRR** (_Trusted Recursive Resolver_) fails. It was set to 2 instead of the default 0. I changed it and still no changes. 
I delved into the settings of Portmaster and found a feature called **[Block Bypassing](https://docs.safing.io/portmaster/settings#filter/preventBypassing)** which blocks Firefox's in-built DNS over HTTPS. I don't want this and even when I disable it, it still uses Dot.

**What did you expect to happen?**
I use Portmaster to block connections for apps because I don't have the option to do that within the app itself. However, I possess the freedom to block ads and trackers, choose the domains I connect to and tweak the settings to my needs when I'm using a browser. So, I don't really need Portmaster to filter stuff on Firefox. I want Firefox to use it's Doh to resolve queries. Disabling the **[Block Bypassing](https://docs.safing.io/portmaster/settings#filter/preventBypassing)** setting doesn't work and when I tried to test with different websites (_shown below_), it shows I still use Dot.
1. [Cloudflare](https://1.1.1.1/help)
2. [Adguard](https://adguard.com/en/test.html)
3. [DNS Leak Test](https://dnsleaktest.com)

**Note**: _This issue persists even in the chromium based browsers I have._ _Example_: **[Brave](https://brave.com/)**
**Doubt:** _I don't know why but I am able to see all the domains I visit on Firefox within Portmaster. I don't want this. This happens even with Doh enabled and also when_ _**[Block Bypassing](https://docs.safing.io/portmaster/settings#filter/preventBypassing)**_ _is disabled._

**Troubleshooting Methods I Used:**
o) Reinstalling Firefox
o) Reinstalling Portmaster
o) Tried different DNS servers
o) Tried Disabling [Block Bypassing](https://docs.safing.io/portmaster/settings#filter/preventBypassing)

**System Information**:
o) 💻 **Windows 10** [_x64_] [_Latest Version_]
o) 🧪 **Portmaster** [_v0.7.14_] [_Latest & Most Stable Version_]
o) 🦊 **Firefox** [_96.0.2_] [_Latest Version_]

> * Doh - DNS over HTTPS

> * Dot - DNS over TLS

**Comment by dhaavi** [comment]
Hey @GeorgeCyriac, thanks for raising this with us.

The only thing the Portmaster does in regards to Firefox is to answer to the [canary domain](https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet), that Firefox should not use DoH itself. The Portmaster needs to see the queries in order to do its work.

We do not do anything special in regards to Chromium based browsers.

The Portmaster does block attempts to talk with DoH/DoT servers as this would circumvent the Portmaster's protections. Software may then decide to fallback to plain DNS.

I see you have already found the Block Bypassing settings. If you disable it for the apps you want it for, it should allow them to use DoH/DoT.
Please note that because of how Windows handles DNS, you will need to disable Block Bypassing in the "System DNS Client" too, in order to also stop blocking bypassing DNS queries - which the Firefox canary domain is.
Hm. Thinking about this, we should probably improve communication here. Tagging w/ @davegson.

When testing, please keep in mind that both the Portmaster and the browsers have caches for pretty much everything. To test a new setting, please delete all caches in both. I don't think that reinstalling is necessary.
This is also why a browser may not switch back to DoH immediately, or the Portmaster can still show you domains for your connections, as it matches them to cached DNS queries.

I also understand that you feel that uBlock is enough for browsing, that is totally valid. I would like to remind you however, that browser extensions cannot block _other_ browser extensions, so there is some added value even if you have uBlock.

Differences between DoT and DoH are minimal and non-existent if you only look at protection from 3rd parties - which is the main purpose.

---

Going forward with testing, lets try one thing at a time - first:
- Disable Block Bypassing for both Firefox and the System DNS Client.
- Restart Firefox (possibly clear caches?)
- Run the DNS leak test again.

PS: Thank you for your very well written issue! It's great to handle such elaborate issues.

**Comment by GeorgeCyriac** [comment]
_Thanks for your prompt reply and for helping me gain insight on the topic._
I found a few [**Firefox articles**](https://www.internetsociety.org/blog/2018/12/dns-privacy-support-in-mozilla-firefox/) discussing the DNS setting in detail and found out that tweaking a few DNS settings in **about:config** actually fixes the issue. 
**o)** Setting **network.trr.mode** to _3_
**o)** Setting **network.trr.bootstrapAddress** to the IP of your DNS [_You might have to create a new_ **[string configuration](https://support.mozilla.org/en-US/kb/about-config-editor-firefox)]**
😊 _Once again, thank you for taking the time to help me._

**Comment by dhaavi** [comment]
Great to hear you solved it!
