### ISSUE TITLE
Not working on a fresh Win10 1904 install

### ISSUE THREAD

**Issue by Netherquark** [safing/portmaster#510]
Just tried out PM on a win10 install I did today, using a vanilla MSFT iso. Its telling me something like a VPN is interfering. I have a pretty standard setup; FTTH, LAN cable to ISP router, with no VPN or proxy configured. I am in India in case thats relevant. How can I fix this? The internet is functional with PM running and not running despite this. I'm on a x86-64 desktop

**Comment by dhaavi** [comment]
Hey @Netherquark, thanks for reporting this issue.

Can you post the Portmaster Debug Info from the settings page?
This might help us see what the problem is.

In general, if you get this notification, something is really wrong with the system integration.
Do you have the feeling that you see all the applications and connections in Portmaster?

**Comment by Netherquark** [comment]
hey im sorry but I actually ended up reinstalling windows on the same machine for different reasons and it seems to be gone now. I think this conflicts with protonvpn. Nonetheless ill install portmaster on my laptop now which has protonvpn and ill update this issue accordingly

**Comment by Netherquark** [comment]
its gone on windows 11 insider preview on my laptop. weird. sorry for the trouble!
