### ISSUE TITLE
Leakage during VPN reconnection?

### ISSUE THREAD

**Issue by TMS-Namespace** [safing/portmaster#520]
Noticed this already multiple times on windows 10 with latest stable version, and Proton VPN.

If I turn off VPN while kill switch is off, or If I turn off kill switch at some point (then vpns usually reconnects), all portmaster rules/configs seems to fail, and applications gets network access even so I blocked them.

Noticed this first when one of the fully blocked applications told me that there is an update, but thought I did something wrong.

After sometime, had to play with kill switch again, and then noticed that my antivirus (which is also blocked fully), got updated its signature DB!

Repeated this couple of times since, so it seems that there is kind of incompatibility between vpns kill switches and portmaster that becomes confused when the switch is turned on/off.

I think this is a very serious problem, if I did not do anything stupid.

**Comment by dhaavi** [comment]
Hey @TMS-Namespace, thanks for reporting this.

I agree, this sounds like a serious problem.

In order to help us dig into this, can you please reproduce the problem and then copy the Debug Info from the affected app just after it happened. You can find the button on the right on the app's page in the network monitor. Then post that here for us to investigate.

Thanks!
