### ISSUE TITLE
Changing (order of) DNS Servers should purge the cache

### ISSUE THREAD

**Issue by northys** [safing/portmaster#548]
**What happened**:

I'm moving NextDNS position in portmaster config from first to last position depending on when I want to test it and I was able to access website which should be blocked by NextDNS because it was previously cached by Cloudflare DNS.

**What did you expect to happen?**:

I would expect that changing DNS servers or their order should lead to portmaster DNS cache purge.

IIRC we had a discussion about a year ago that portmaster doesn't offer such feature (DNS purging) and that the only way to do it currently is to query the same DNS 3 times in a row. If is still true this can't be fixed.

**Comment by boistordu** [comment]
relating to my problem 
https://github.com/safing/portmaster/issues/543
Since I4ve mentionned to have done that and which didn't result to the same problem. So clearly it's a whole distribution system which is at fault

**Comment by dhaavi** [comment]
You can clear the DNS cache from the menu in the version of the settings page.

The Portmaster only uses cached entries if the resolver used is still configured - otherwise the cached entry will be disregarded and a new query will be sent.

The thing with the 3 queries in a row is an attempt to detect user frustration and not a proper solution. ;)

I feel #543 is a bit different than this.

**Comment by northys** [comment]
@dhaavi doesnt it make sence for you to trigger the cache prune atuomatically after you change the order in UI as I described in first post?

**Comment by dhaavi** [comment]
Yes, this is probably a good idea.

Users will expect the earlier resolvers to resolve an address. Even if the cache is still valid, this will lead to confusing when users quickly try different settings.
