### ISSUE TITLE
Problem using Portmaster with PIA VPN

### ISSUE THREAD

**Issue by Pay-ola** [safing/portmaster#587]
**What happened**: Ioss of network connection to the network after turning on PIA with OpenVPN and Wireguard while postmaster is installed. Looked at other reports and couldn't find a solution sadly. Any help would be great!

**Comment by xadamentx** [comment]
Had the same Issue (well at least similar) but fixed it by changing the DNS within the PIA app to use the existing server & using OpenVPN. I've never actually lost connection to the PIA network, DNS was simply not working. Might help in your case as well though.

**Comment by Pay-ola** [comment]
Changed settings to OpenVPN and to use existing server but it still keeps my network offline when both apps(PIA vpn on) are running at the same time. 

> Had the same Issue (well at least similar) but fixed it by changing the DNS within the PIA app to use the existing server & using OpenVPN. I've never actually lost connection to the PIA network, DNS was simply not working. Might help in your case as well though.

**Comment by dhaavi** [comment]
Hey @Pay-ola, thanks for reporting this!

We have handled issues with PIA in three different cases in the past - maybe one will give you a helpful pointer:
https://github.com/safing/portmaster/issues/512
https://github.com/safing/portmaster/issues/323
https://github.com/safing/portmaster/issues/317

It is hard to make a suggestion with the little information you provided. To get into more depths with your problem, please post the debug info (copied from the settings page) _while_ the issue is occurring. Thanks!

**Comment by dhaavi** [comment]
Also - I forgot the mention that in my last comment - thanks a lot @xadamentx for chiming in here and helping to find a solution!

**Comment by Pay-ola** [comment]
> 

Sent the debug info using the portmaster report bug feature.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
