### ISSUE TITLE
[Feature] Add Quality of Service QoS

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#616]
@davegson https://en.wikipedia.org/wiki/Quality_of_service

**Comment by dhaavi** [comment]
Hey @Rexadev, thanks for the suggestion.

This can mean many things, can you please go into more detail, outlining a user story and a use case?

**Comment by Rexadev** [comment]
@dhaavi Example, 
Port based - I want DNS (port 53,853, for DoH some specific domain over 443) to take highest priority.
Domain based - I want my music player to not stop at the cost of making websites slow so I may give priority to music.youtube.com, spotify.com.
App Based -  I want games to have highest priority.

Within these 3 QoS methods priority order is Port>Domain>App

**Comment by davegson** [comment]
could you write what the abbreviation "QoS" stands for? It is difficult to follow without knowing that.

**Comment by dhaavi** [comment]
From a technical view point: From what I understood of the use case, this is very difficult to implement - be it with or without the SPN, because shared networks have no defined capacity and vary heavily in load. This means that implementing anything like this is a big challenge in regards to (1) feasibility, (2) performance and (3) configuration. A lite version may of this may be found in the SPN some day - no promises.

**Comment by Rexadev** [comment]
@dhaavi There are some apps on WIndows having QoS and Bandwisth control example `NetLimit` and `c_FosSpeeed `
