### ISSUE TITLE
403 forbidden when accessing control panel from localhost

### ISSUE THREAD

**Issue by northys** [safing/portmaster#63]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:

1) installed postmaster using deb package downloaded from official website - https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.deb
2) opened http://localhost:817/ and got "Forbidden"

```
curl -vvv http://localhost:817/
*   Trying 127.0.0.1:817...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 817 (#0)
> GET / HTTP/1.1
> Host: localhost:817
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 02 Jun 2020 23:55:57 GMT
< Content-Length: 10
< 
Forbidden
* Connection #0 to host localhost left intact
```

**What you expected to happen**:

See control panel in my browser instead of 403.

**How to reproduce it (as minimally and precisely as possible)**:

Please see **What happened** and **Operating System**.

**Anything else we need to know?**:

I used to use nextdns client which was killed on portmaster startup. I've got notification about it in loop because systemd always started nextdns again so I had to uninstall nextdns client and reboot my computer.

**Environment**:

Portmaster Version: 

**I know there is already version v0.4.3 but the official deb package contains 0.3.4 and `portmaster-control update` returns only `200603 02:06:12.222 ▶ BOF`.**

```
# cannot post version summary from control panel because it's not working :)
portmaster-control --ver
0.3.4
```

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [ ] Windows 10
- [x] Linux

```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.

```
jun 03 01:55:57 northys-laptop portmaster-control[1423]: 200603 01:55:57.119 entication:089 ▶ WARN 647 api: denying api access to 127.0.0.1:59560
```

**Comment by ppacher** [comment]
Hi @northys,

Thanks for getting back to use. The `403 Forbidden` error is expected because the Portmaster does not allow the browser to access it's API. For security reasons the Portmaster only allows it's application (`portmaster-control run app`) to access it. Moreover, the HTTP server started at port 817 does not contain the user interface, it only contains an API endpoint for controlling the Portmaster. 

Access to the the API is restricted to the Portmaster App (UI) so it's not possible for other applications to disable the firewall. Please try the user interface via `portmaster-control run app`.

`portmaster-control --ver` only returns the version of the `portmaster-control` tool, not the portmaster service itself. You can check all the versions in the "About" page on the Portmasters UI.

**Comment by ppacher** [comment]
Regarding the nextdns/systemd issue. The Portmaster currently does a hard takeover by killing the processes that currently listens on port `:53`. It should be enough to stop the nextdns client using `systemctl stop nextdns` and disable it (`systemctl disable nextdns`) so it doesn't start on boot.

**Comment by northys** [comment]
Hi @ppacher,

the same "Forbidden" text on white page is shown even when I start the Portmaster app installed from deb - opened from gnome search. This was the reason why I started digging around to see what port is accessed and what IP it is listening on so opened it in my browser. I also tried the `portmaster-control run app` which ended on Forbidden page too.

I've solved nextdns client by running `nextdns uninstall`. I think it just masks the systemd service. I mentioned it just in case it could be source of potential problems

**Comment by dhaavi** [comment]
Hey @northys, this should definitely not happen. The Portmaster itself should be able to access itself. I just tried to reproduce this issue but was unable to do so.

Before we further troubleshoot that, I'd like to clarify and explain some other things:

As @ppacher already mentioned, `portmaster-control` and `portmaster-core` are two different things. The `portmaster-control` is a service wrapper and `portmaster-core` is the actual Portmaster doing all the work.

Currently, the API authentication is done on a executable path basis. Every executable that resides within the Portmaster data directory - `/var/lib/portmaster` in this case - is allowed to access the API. Whenever an executable outside this directory tries to access the API, the Portmaster returns `443 Forbidden`. We will improve this error message to provide more information here - tracked via #64.

If you'd like access the UI with your browser, you could turn on development mode, which will deactivate the API authentication. You might have to switch the expertise level to `developer` in order to see that setting - or use the quick switches in the upper right hand corner.

I have also opened an idea evaluation issue - #65 - to find out if there is a need to add a mechanism to exempt/extend the API authentication.

You said that you got the notification that nextdns was killed in a loop. Did this only happen when you restarted the Portmaster or all by itself? If so, nextdns may be doing the same thing and was killing the Portmaster in the same manner. If that is the case, we will have to do more investigation here. Thank you for mentioning this.
The Portmaster only checks for a conflicting service on startup (or when the internal nameserver fails).

Ok. So let's get back to the issue at hand:

The Portmaster somehow does not correctly detect who is accessing the API. Unfortunately, the log line that would help us here is a debug level log, so you will have to manually start the Portmaster once in order to find out what is happening.

This log line we are looking for:
https://github.com/safing/portmaster/blob/328884c354d167ae1b5aa7ca862c3085d9fc47c0/firewall/api.go#L97

To start the Portmaster manually, please first stop the running instance with `sudo systemctl stop portmaster`, then execute `sudo /var/lib/portmaster/portmaster-control run core --data /var/lib/portmaster --log debug`.
Then please open the App again and look out for the log line.

When done, you can start the Portmaster in the background again using `sudo systemctl start portmaster`

**Comment by northys** [comment]
Hi,

thanks for your help! I see that `portmaster-control` in my `$PATH` is different than `portmaster-control` in `/var/lib/portmaster`. But running portmaster app using `/var/lib/portmaster/portmaster-control run app` results in same Forbidden page (connecting to api running from systemd without debug).

Those 2 portmaster-controls are not even symlinked. Is there a reason for that?

```
northys at northys-laptop in ~
» file /usr/bin/portmaster-control
/usr/bin/portmaster-control: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=lXYZtTr85hH1CvtzPCMj/RwKJrkBscahVMOUJ7Mvm/q9rY2j6U4IbgUGP-r3JE/cc0X8MWUAD_FilbSAhfL, not stripped
northys at northys-laptop in ~
» file /var/lib/portmaster/portmaster-control 
/var/lib/portmaster/portmaster-control: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=lXYZtTr85hH1CvtzPCMj/RwKJrkBscahVMOUJ7Mvm/q9rY2j6U4IbgUGP-r3JE/cc0X8MWUAD_FilbSAhfL, not stripped
northys at northys-laptop in ~
» ll /usr/bin/portmaster-control
-rwxr-xr-x 1 root root 12M čen  3 01:28 /usr/bin/portmaster-control*
northys at northys-laptop in ~
» ll /var/lib/portmaster/portmaster-control
-rwxr-xr-x 1 root root 12M čen  3 01:28 /var/lib/portmaster/portmaster-control*
```
---

I did what you asked me to do - I've started portmaster in debug mode. The result is the same Forbidden page, sadly.

Logs produced by portmaster during period between open / close of the app (opened using gnome desktop shortcut).

```
200603 13:32:04.212 terception:121 ▶ DEBU 189 accepting local dns: OUT UDP 127.0.0.1:40968 <-> 127.0.0.53:53
200603 13:32:04.212 terception:121 ▶ DEBU 190 accepting local dns: OUT UDP 127.0.0.1:40968 <-> 127.0.0.53:53
200603 13:32:04.218 connection:198 ▶ INFO 191 filter: granting connection root:/usr/lib/snapd/snapd:1431 to api.snapcraft.io. (<nil>), endpoint is not blacklisted (default=permit)
200603 13:32:04.218 nameserver:291 ▶ DEBU 192 nameserver: returning response api.snapcraft.io.A to root:/usr/lib/snapd/snapd:1431
200603 13:32:04.221 connection:198 ▶ INFO 193 filter: granting connection root:/usr/lib/snapd/snapd:1431 to api.snapcraft.io. (<nil>), endpoint is not blacklisted (default=permit)
200603 13:32:04.221 nameserver:291 ▶ DEBU 194 nameserver: returning response api.snapcraft.io.AAAA to root:/usr/lib/snapd/snapd:1431
200603 13:32:04.226 connection:198 ▶ INFO 195 filter: granting connection root:/usr/lib/snapd/snapd:1431 to api.snapcraft.io. (91.189.92.38), endpoint is not blacklisted (default=permit)
200603 13:32:04.939 terception:129 ▶ DEBU 196 accepting api connection: OUT TCP 127.0.0.1:32808 <-> 127.0.0.1:817
200603 13:32:04.978 rewall/api:097 ▶ DEBU 197 filter: denying api access to  - also checked   (trusted root is /var/lib/portmaster)
200603 13:32:04.978 entication:089 ▶ WARN 198 api: denying api access to 127.0.0.1:32808
200603 13:32:05.979 terception:129 ▶ DEBU 199 accepting api connection: OUT TCP 127.0.0.1:32810 <-> 127.0.0.1:817
200603 13:32:05.987 d-response:051 ▶ INFO 200 api request: 127.0.0.1:32810 HIJ /api/database/v1
200603 13:32:05.987 i/database:084 ▶ INFO 201 api request: init websocket 127.0.0.1:32810 /api/database/v1
200603 13:32:06.327 terception:129 ▶ DEBU 202 accepting api connection: OUT TCP 127.0.0.1:32812 <-> 127.0.0.1:817
200603 13:32:06.351 rewall/api:097 ▶ DEBU 203 filter: denying api access to  - also checked   (trusted root is /var/lib/portmaster)
200603 13:32:06.351 entication:089 ▶ WARN 204 api: denying api access to 127.0.0.1:32812
200603 13:32:08.786 connection:198 ▶ INFO 205 filter: granting connection northys:/usr/bin/nextcloud:3024 -> 10.10.0.3, endpoint is not blacklisted (default=permit)
200603 13:32:09.257 i/database:131 ▶ WARN 206 api: websocket write error: websocket: close 1006 (abnormal closure): unexpected EOF
```

I've also tried to run the client app from console using the binary I found in `/var/lib/portmaster` with same result:

![Screenshot from 2020-06-03 13-34-55](https://user-images.githubusercontent.com/2878126/83632162-0fb31880-a59f-11ea-9160-7ccffcf70dd3.png)

Logs produced by api running in debug mode:

```
200603 13:39:21.260 rewall/api:097 ▶ DEBU 261 filter: denying api access to  - also checked   (trusted root is /var/lib/portmaster)
200603 13:39:21.260 entication:089 ▶ WARN 262 api: denying api access to 127.0.0.1:33134
200603 13:39:22.261 terception:129 ▶ DEBU 263 accepting api connection: OUT TCP 127.0.0.1:33136 <-> 127.0.0.1:817
200603 13:39:22.271 d-response:051 ▶ INFO 264 api request: 127.0.0.1:33136 HIJ /api/database/v1
200603 13:39:22.271 i/database:084 ▶ INFO 265 api request: init websocket 127.0.0.1:33136 /api/database/v1
200603 13:39:22.592 terception:129 ▶ DEBU 266 accepting api connection: OUT TCP 127.0.0.1:33138 <-> 127.0.0.1:817
200603 13:39:22.641 rewall/api:097 ▶ DEBU 267 filter: denying api access to  - also checked   (trusted root is /var/lib/portmaster)
200603 13:39:22.641 entication:089 ▶ WARN 268 api: denying api access to 127.0.0.1:33138
200603 13:39:24.073 connection:198 ▶ INFO 269 filter: granting connection systemd-timesync:/usr/lib/systemd/systemd-timesyncd:1335 to ntp.ubuntu.com. (91.189.91.157), endpoint is not blacklisted (default=permit)
200603 13:39:24.086 i/database:131 ▶ WARN 270 api: websocket write error: websocket: close 1006 (abnormal closure): unexpected EOF
```

**Comment by dhaavi** [comment]
I found a fix for this - underway in PR https://github.com/safing/portmaster/pull/66. After successful review, I will release a new version with this fix.

I will go into more detail tomorrow, just wanted to let you know.

**Comment by dhaavi** [comment]
I also found a workaround that _could_ work for you: Right click the window and select "Reload". I have found that this (sometimes?) works.

**Comment by northys** [comment]
> I also found a workaround that _could_ work for you: Right click the window and select "Reload". I have found that this (sometimes?) works.

It works! And it looks great considering it's just an alpha version =)

**Comment by dhaavi** [comment]
Ok, so this took a bit longer than expected. But I was able to find the real problem: On linux, getting the socket inode and PID of a connection are two distinct steps. We retry getting the socket, but did not retry getting the PID of that socket inode. We also added some other improvements to help with the App<>Core Communication.

This is now fixed with 9f42e6ff93b0b90ab8a2fce33391f7dc0c2b447e and should work in v0.4.8.
In order to apply the update, press the update button on the dashboard, followed by the restart button when prompted.

Please report if this really also solves the problem on your end.

**Comment by northys** [comment]
I can confirm the dashboard loads immediately with no 403 after upgrading to v0.4.8. Thanks for fast fix!

**Comment by northys** [comment]
@dhaavi I just wanna to share a little snippet which you can send to users later so they can run the portmaster in trace mode.

> To start the Portmaster manually, please first stop the running instance with sudo systemctl stop portmaster, then execute sudo /var/lib/portmaster/portmaster-control run core --data /var/lib/portmaster --log debug.

There's systemd way:

```
systemctl edit portmaster.service
```

Add following content to file that opened:
```
[Service]
ExecStart=     # this empty line has to be there otherwise the following command would concatenate to the original one I think
ExecStart=/usr/bin/portmaster-control run core --data=/var/lib/portmaster/ --log debug
```

And restart your service:
```
systemctl restart portmaster.service
```

**Comment by ppacher** [comment]
Thanks for adding this here @northys! We already have https://github.com/safing/portmaster-packaging/issues/2 that's meant for improving the systemd unit file. I'll change the log-level to an Environment= setting there so changing that should become even more simple with `systemctl edit portmaster.service`:

```ini
[Service]
Environment= LOG=debug
```

**Comment by northys** [comment]
@dhaavi I foud a regression of this issue on WIndows.

> I also found a workaround that could work for you: Right click the window and select "Reload". I have found that this (sometimes?) works.

This workaround works. There is "refresh page" link instead of refreshing the page from context menu.

**Comment by ppacher** [comment]
Hi @northys,

thanks for reporting the regression.

Did this happen after a fresh installation (i.e. the first time the UI have been opened) or did it work before and just broke from one moment to the other? I'm curios because AFAIK we didn't touch anything on the API auth part lately.

**Comment by dhaavi** [comment]
As the workaround worked, I don't think that there is any new problem here, only what has always been the case: It can always happen that for some reason the Portmaster cannot attribute the connection to the process, and therefore just denies it.
This can be the case if the kernel is too slow in updating the internal network states.

Until the new UI is here, this problem will arise from time to time.

**Comment by northys** [comment]
@dhaavi the dashboard either works (I had few cases when it opened for firsttime), it says "server refused connection" and then the workaround works or it says (the IE embeded) that localhost:dunnoThePort is not listening at all.

**Comment by northys** [comment]
I'm closing this because it always works when I run portmaster manually. I think it is related to problems in #161
