### ISSUE TITLE
Add option to enforce safe search on all browsers

### ISSUE THREAD

**Issue by itsnotsaved** [safing/portmaster#633]
**What would you like to add or change?**:

Portmaster comes with NSFW filters as part of privacy filter (Privacy filter --> Filter lists --> nsfw then this is another feature related to it.

Privacy filter --> Advanced --> Enforce safe search
Add "Enforce safe search" feature (enforce safe search on all browsers for safe search supported sites)

Sites: google, youtube, dukdukgo, yandex, bing, pixabay

**Comment by itsnotsaved** [comment]
https://github.com/safing/portmaster/issues/611

**Comment by p2anav** [comment]
Thanks for this great suggestion. Enforcing safe search using filter lists would require some remapping, which may work for something like duckduckgo.com to safe.duckduckgo.com, but I am not sure if every search engine would keep a subdomain for safe search. I see that google allows you to turn safe search ON/OFF at https://www.google.com/safesearch. Other search engines may use query parameters and so on. Due to this complexity, I am not sure if there is a straight forward solution but I am interested to know if some other software has already implemented this using filter lists.

**Comment by itsnotsaved** [comment]
@p2anav Check settings to see that option https://adguard.com/en/adguard-windows/overview.html it's proprietary windows, mac supported software and can your team work to implement https://github.com/safing/portmaster/issues/611#issuecomment-1113525706  **what still need** features to this opensource software?

**Comment by itsnotsaved** [comment]
>implemented this using filter lists.

sorry; i didn't read your message correctly

**Comment by p2anav** [comment]
> sorry; i didn't read your message correctly

No issues.

and thanks for sharing the link.
