### ISSUE TITLE
[Suggestion] Ask for DNS change

### ISSUE THREAD

**Issue by throny** [safing/portmaster#642]
**What would you like to add or change?**:
Before setting Cloudflare DNS as a default, ask the user. Some of them like me have a PiHole+unbound in their current configuration. (as this is not even shown in the basic view of Portmaster, a little hint would be great)
It would be awesome to select one of the multiple DNS service providers out there at first launch. 

**Why do you and others need this?**:
It would be useful to know when the DNS provider changed so users with their own resolver can opt-out.

**Comment by davegson** [comment]
Hey there, thanks for using the PM and for your suggestion!

I do agree, it is important to at least _inform_ users about what the Portmaster does. We actually implemented onboarding screens in the recent 0.8.8 version. This should fit your need I think.

It's an intro screen which gives an overview of what the PM does and also gives you the option to quickly change the DNS.

Could you check the newest version by setting your [Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel) to Beta - and then tell if that is what you were after?

**Comment by throny** [comment]
Hi Dave,

first of all - thanks for the quick reply. 
That's what I would expect, right! The onboarding part was completely missing imho so this is a huge improvement!

However, as one coming from simplewall, I am not quite picked up yet. It would be great to decide on first launch if one would like a whitelist mode. I switched to "Prompt" mode but unfortunately it shows multiple prompts at the same time if you don't have a whitelist yet.
For applications connecting to a lot of destinations it is barely possible to handle it with prompts. I would expect a additional button like  "Allow for Application" instead of allowing every destination seperately.

**Comment by davegson** [comment]
Happy this was what you expected! Hence I'm closing this issue.

In terms of your other input, thanks! This helps us understand our users better.

> It would be great to decide on first launch if one would like a whitelist mode.

I am unsure since many people will not understand "black/whitelist mode"/"block/allow mode". Kinda overwhelming for non-technical people. And technical people usually find the prompt mode ;)

> For applications connecting to a lot of destinations it is barely possible to handle it with prompts. I would expect a additional button like "Allow for Application" instead of allowing every destination seperately.

We know "Prompt" is unpleasant at best, a pain in the a** at worst :)

There are issues around this, as an example, you can set the [Default Network Action](https://docs.safing.io/portmaster/settings#filter/defaultAction) to "Allow " for a specific app. Just have to open the app page and then go into its settings.

We also know you currently have to click a lot in order to get things done - that and other things in the UI/UX is something we plan to improve in the Beta phase. For now the focus lies more on technical stability.

Anyway, I took note of your input - feel free to add other suggestions as you get ideas. Much appreciated - have a good one!
