### ISSUE TITLE
"Trusted DNS" Servers

### ISSUE THREAD

**Issue by smathieson** [safing/portmaster#661]
**What would you like to add or change?**:
Add some sort of feature whereby some DNS servers can be added as "trusted". Perhaps link the DNS IP to the server/router MAC address somehow to make sure these are the right servers. It is not infallible, I know since MACs can be spoofed, but it would allow some level of protection.

**Why do you and others need this?**:
I would like to have my DNS queries private and encrypted when in public networks, however in the office network the DNS server is configured with local resources for certain computers. This is ignored if DNS servers are set.

**Comment by dhaavi** [comment]
Hey @smathieson, thanks for your suggestion!

I think this is a very good use case, which also seems non trivial to solve it in a way that provides good UX.

We are planning to build some sort of profle system - sets of settings that you can manually or automatically activate based on your environment. This will take some time though until we get there and until we find a really good solution for it.
This system then could add/remove DNS servers based on your network.

For now, you can try this solution:
If you can change the office network, you could add the domains you use in that network as "search domains" to the resolver (probably in the DHCP config), the Portmaster will import the resolvers from the system and prioritize them for the defined search domains of the resolver.
And because it comes from the network it is configured automatically when you enter the network and is removed when you leave the network.
