### ISSUE TITLE
Allow bypassing or disabling Portmaster DNS management

### ISSUE THREAD

**Issue by catwithbanana** [safing/portmaster#677]
**What would you like to add or change?**:
Currently, the only way to use Portmaster alongside Mullvad is to set Mullvad to a custom DNS that Portmaster manages. I'm interested in using _just_ the firewall functionality of portmaster, however, or at least somehow setting up a configuration where the VPN's DNS is used when the VPN is active.

Ideally when Mullvad is active my system would use Mullvad DNS, and when it's disabled it would fall back to whatever I configure in Portmaster.

As a compromise it would be good to be able to use the firewall and filter list features of Portmaster without having it fuss with DNS management (essentially making it the equivalent of Little Snitch on MacOS)

**Why do you and others need this?**:
When using a VPN it's best to use the VPN's built in DNS to avoid standing out from the crowd. When not using a VPN, though, any number of providers can be used for any number of reasons.

The product Little Snitch on MacOS shows how compelling a just-filtering-and-blocking program can be.

**Comment by NubsParrot** [comment]
Try disabling Secure DNS in Portmaster.

**Comment by catwithbanana** [comment]
I see how to remove my configured DNS servers, but not anywhere to disable SecureDNS completely.

![image](https://user-images.githubusercontent.com/75995110/171684345-21db763c-fed8-4ace-8dd4-e845428508e6.png)

Removing the servers doesn't seem to fix the issue -- I still have to set CustomDNS in Mullvad to get internet access.

**Comment by NubsParrot** [comment]
Change simple interface to advanced interface. Disable Secure DNS, and if that doesn't work scroll down to the bottom and disable bypassing. I feel one of those situations would allow for your use-case. might not though.

**Comment by dhaavi** [comment]
Hey @catwithbanana, thanks for raising this issue here.

Unfortunately, it is not possible disable the Secure DNS part, as it is a required part of Portmaster so that it can work correctly.

There is a new rather hidden setting you can use to disable the [Seamless DNS Integration](https://docs.safing.io/portmaster/settings#filter/dnsQueryInterception). However, you then must take care of correct integration yourself. If DNS queries are not sent to Portmaster at some point, it will not be able to protect you with all features.

Additionally, if it detects that this is the case, it will scream at you until you fix that.

**Comment by catwithbanana** [comment]
So if I understand correctly, the DNS management is integral to Portmaster's ability to revoke net access to programs, so it could never function quite like Little Snitch?

**Comment by dhaavi** [comment]
The DNS management is integral to Portmaster's ability to know the target domain name of a connection. All features that need the domain - eg. Rules and Filter Lists - will only work correctly if that data is present.
Some other features work well without this data, but as Rules and Filter Lists are two of the big features, it's easier to require the DNS management in order to avoid confusion - and with it - privacy risks.
Portmaster will gain the ability to extract domain name information from connections to some extent in the future, but this data is hidden more and more by the connections, especially with TLS1.3 coming, this will become harder again, thus going back to requiring the DNS management.

**Comment by catwithbanana** [comment]
Got it, thanks. I will pursue a different solution for my needs. I appreciate your hard work.
