### ISSUE TITLE
Allow filtering the network monitor overview

### ISSUE THREAD

**Issue by NicolasGoeddel** [safing/portmaster#683]
**What would you like to add or change?**:
Allow filtering the network monitor overview.
![grafik](https://user-images.githubusercontent.com/1520064/172338704-5eae6a93-731f-4472-83a3-524f04e304bb.png)

**Why do you and others need this?**:
Sometimes there were lots of connection in the last 10 minutes and that green/grey bar showing allowed/blocked connections looks completely green although a few blocks occurred (see image below).
![grafik](https://user-images.githubusercontent.com/1520064/172338551-e170fc7b-8205-4b19-bde1-1bf2ceaa6588.png)
It would be nice to make this more visible or adding a filter which allows you to only show blocked connections in the overview.

**Comment by p2anav** [comment]
Nice idea. I will pass it on to the team.

**Comment by davegson** [comment]
Hey there,

thanks for your using the PM and for your input - great ideas btw!

Good news, we are actually already working on a feature for a full-device "Network Activity" overview, where you will see all connections of your device (from the last 10 minutes) with filtering included.

This needed some technical restructuring because it's more tricky to show 1000s of connections compared to 100s with higher usage apps.

Anyway, looking very much forward to release it, should only be a few weeks + 2 weeks where it's tested in the Beta [Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel).

PS: also, when there are blocked connections it _should_ show a bit of grey in the bar... If this happens frequently please create a bug report.

**Comment by davegson** [comment]
fyi, this move into the "Beta" [Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel)
