### ISSUE TITLE
Captive portal doesn't work in train

### ISSUE THREAD

**Issue by northys** [safing/portmaster#694]
**What happened**:

![image](https://user-images.githubusercontent.com/2878126/173295607-3118b7c9-40e7-4de4-9c27-1ba77cd397fa.png)

```
dig railnet.obb.at

; <<>> DiG 9.18.1-1ubuntu1.1-Ubuntu <<>> railnet.obb.at
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**What did you expect to happen?**:

When portmaster detects captive portal it should:
1) use DHCP list of DNS servers and block all other connections to prevent DNS leak
2) let user finish captive
3) which back to user-defined list of DNS servers and unblock all other connections

**How did you reproduce it?**:

Use train Wi-Fi in ÖBB trains with DNS set to 1.1.1.1.

**Debug Information**:
https://support.safing.io/privatebin/?d9ec600303e687aa#9XS185K94cBv2pSmaPaxrH2mfLp3yt2W3nu3v9yHR468

**Comment by dhaavi** [comment]
Hey @northys, thanks for reporting! I remember something about this use case.

Note: In the `dig` command you forgot an `e` in the domain.

> When portmaster detects captive portal it should:
> 
> 1. use DHCP list of DNS servers

This is the case.

> block all other connections to prevent DNS leak

This is a difficult one. The user might want to enable a VPN that can circumvent the portal.
Not sure how to best handle this.
This a situation with multitudes of edge cases.
Leaks should not happen when the portal is "solved" in an acceptable time.
At some point, Portmaster might fall back to system DNS, but this is also subject to change in order to better prevent leaks.

---

I think one thing that happened back then was that their network used the same ranges as docker. But it seems from the browser error that this was indeed a DNS lookup failure.
