### ISSUE TITLE
DNS response TTL is dropped and always returns 17

### ISSUE THREAD

**Issue by northys** [safing/portmaster#74]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:

When using portmaster as local DNS every query returns TTL 17 no matter what actual TTL is.

**What you expected to happen**:

Repeated dig calls every second should count the TTL down to 0. 

**How to reproduce it (as minimally and precisely as possible)**:

Install portmaster on Ubuntu (or probably any other OS) and make DNS query using dig or similar tool. Then try the same with nextdns client / cloudflare client / default dnsmasq...

```
// ensure next dns is running
northys at northys-laptop in ~
» sudo nextdns status
running

// query root.cz multiple times and get lower TTL each call - 600, 598, 595... I've removed all but answer section from dig output to make it readable
northys at northys-laptop in ~
» dig root.cz
;; ANSWER SECTION:
root.cz.		600	IN	A	91.213.160.188

northys at northys-laptop in ~
» dig root.cz
;; ANSWER SECTION:
root.cz.		598	IN	A	91.213.160.188

northys at northys-laptop in ~
» dig root.cz
;; ANSWER SECTION:
root.cz.		595	IN	A	91.213.160.188



// stop nextdns and start portmaster to use it as local dns
northys at northys-laptop in ~
» sudo systemctl stop nextdns.service 
northys at northys-laptop in ~
» sudo systemctl start portmaster.service 

// sudenly all calls returns ttl 17 no matter what DNS I try to use (quad9, cloudflare..). you can see that it is making actual DNS queries with no cache because it took around 150ms for each query to finish
northys at northys-laptop in ~
» dig root.cz
;; ANSWER SECTION:
root.cz.		17	IN	A	91.213.160.188

;; Query time: 132 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: So čen 06 00:37:00 CEST 2020
;; MSG SIZE  rcvd: 48

northys at northys-laptop in ~
» dig root.cz
;; ANSWER SECTION:
root.cz.		17	IN	A	91.213.160.188

;; Query time: 144 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: So čen 06 00:44:13 CEST 2020
;; MSG SIZE  rcvd: 48

northys at northys-laptop in ~
» dig root.cz
;; ANSWER SECTION:
root.cz.		17	IN	A	91.213.160.188

;; Query time: 156 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: So čen 06 00:44:20 CEST 2020
;; MSG SIZE  rcvd: 48
``` 

**Anything else we need to know?**:

**Environment**:

```
Name: Portmaster
Version: 0.4.8
Commit: tags/v0.4.8-0-g88322262d863b749b643402fb6de0c6f38495299
Build Options: main.go
Build User: user
Build Host: docker
Build Date: 05.06.2020
Build Source: https://github.com/Safing/portmaster
```

**Operating System:**
- [ ] Windows 7
- [ ] Windows 8/8.1
- [ ] Windows 10
- [x] Linux

```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.

**Comment by dhaavi** [comment]
Hey @northys, I see you are really digging into the Portmaster. Great!

This is actually intended behavior. We set the TTL to `17` for two reasons:
- To signify that the query was handled by the Portmaster.
  - This is especially important when we intercept queries. (Try `dig root.cz @1.1.1.1`)
  - We think that this is will be especially helpful when troubleshooting network issues.
- In order to improve correlation between domains and connections it's important that the programs query DNS often.
  - We will additionally check the SNI header in the future, but SNI is not always used, even if supported by the protocol.

The Portmaster still does cache everything as long as specified. If you check the logs, it will tell you whenever it takes a response from cache and how long that response is still valid. I think you'll have to set the log level to `trace` though. So you will have to manually start the Portmaster Core with `portmaster-control run core --data /var/lib/portmaster -log trace`.

We actually came to use the number `17` at numerous places to signify that the Portmaster was in play or that the Portmaster was involved directly.

Regarding the issue: Is this just something you notices, or do you require the resolver to return the real TLLs? If so, please elaborate on that. Does it break a script? Does it break your workflow? I'd like to understand the impact you have of this.

Side Note: One thing we additionally do is to serve TXT records in the additional section to deliver additional information about the query, especially when it was or could have been blocked. Try querying a domain that you block or is blocked by a filterlist!

**Comment by northys** [comment]
Hey @dhaavi, sorry for the delay!

I understand reasons why portmaster is doing this. Thanks for the explanation!

> The Portmaster still does cache everything as long as specified. If you check the logs, it will tell you whenever it takes a response from cache and how long that response is still valid.

I haven't actually tried running the core in trace log verbosity but I think the cache is not being used because each query took around 100-200ms. I would expect <10ms response time when using local portmaster cache. Default dnsmasq setup on ubuntu responses in 0ms - measured by dig.

> We actually came to use the number 17 at numerous places to signify that the Portmaster was in play or that the Portmaster was involved directly.

I guess the number came with Gate17 which I can see in your GitHub profile. Gate17 is predecessor of Portmaster? I wasn't able to figure it out from what I've googled.

> Regarding the issue: Is this just something you notices, or do you require the resolver to return the real TLLs? If so, please elaborate on that. Does it break a script? Does it break your workflow? I'd like to understand the impact you have of this.

It's just something I have noticed. I'm used to see real TTL so when I change domain I can expect the same result for all customers when querying 8.8.8.8 or 1.1.1.1. When my local cache expires then probably cache for all users will expire soon so I can for example run ACME challenge without getting banned for too many failed attempts.

I would love portmaster if portmaster could return the real TTL (the one from cache or the actual one when no cache is used) in the TXT answer section so I don't have to use "dig online" services? Also it could contain the information about queries being intercept. That would be really great I think =)

```
dig northys.cz

; <<>> DiG 9.16.1-Ubuntu <<>> northys.cz
;; QUESTION SECTION:
;northys.cz.	IN	A

;; ANSWER SECTION:
northys.cz. 0 IN	A	999.999.999.999

;; ADDITIONAL SECTION:
northys.cz. 0 IN	TXT	"cache hit" // cache miss
northys.cz. 0 IN	TXT	"TTL 600"
```

**Comment by davegson** [comment]
Quickly chiming in for:

> I guess the number came from Gate17 which I can see mentioned in your GitHub profile. Gate17 is predecessor of Portmaster? I wasn't able to figure it out from what I've googled so far.

Almost! Gate17 was the previous name for the Safing Privacy Network (SPN), as you can see from [our design in 2017](https://safing.io/assets/img/archive/previous_designs/homepage_retro.jpg), whereas Portmaster was the name specifically for the Privacy Filter. And before Gate17, it was named Port17, which got renamed because it was too similar to the Portmaster. So yeah, over the years we grew really fond of the number 17. So even though we dropped the name you'll probably come across it from time to time.

Nowadays we call the whole app Portmaster, while the specific features having "generic" names. It feels that simplifies things.

Hope you enjoyed some Safing lore ;) - Daniel will follow up on the technical questions.

PS: Gate17 still exists in [our Whitepaper](https://safing.io/files/whitepaper/Gate17.pdf), but also that will expire one day. ;)

**Comment by northys** [comment]
> Hope you enjoyed some Safing lore ;)

Thanks =)

**Comment by northys** [comment]
> I tested this and got between 100 and 120ms response time with dig for a cached response. When I turned off process detection I had a response time of 0-1ms for a cached record and 40-80ms for a new request.

I can confirm that. I had to enable process detection to access the dashboard though.

@dhaavi thanks for opening new issues based on this ticket! I think I can close this one.

**Comment by dhaavi** [comment]
Ah, yes.
For the future: Enabling development mode would have made the dashboard accessible, because disabling process detection breaks authentication.
