### ISSUE TITLE
A message from ProtonVPN to Portmaster

### ISSUE THREAD

**Issue by FrostBlade5** [safing/portmaster#777]
Hello,

Thank you for the further explanation from your side, now I better understand the situation and your approach towards securing your connection. 
Unfortunately, I could not provide any support outside the Proton VPN environment, as I am unfamiliar with your device, services and network setup and I cannot provide accurate instructions on how to execute the desirable outcome. 

In this case, since the Proton VPN application cannot be optimized to the priority level per your customization, you can consider contacting the Portmaster Customer Support Team. 
If you are referring to the Safing Portmaster service, I noticed that they are in the Alpha stage and as mentioned from their side, bugs can be experienced. 
You can consider potentially providing your feedback to their Customer Support team about your experience as this might generally help the situation and they can let you know if there is a possibility of the changes that you wish to apply for DNS. 

-Personal note, the above email was a response from ptoonvpn support after i asked them how i can make protonvpn overwrite portmasters dns server. I still DO NOT have a solution for this issue.

**Comment by davegson** [comment]
Hey there,

I feel your frustration - sorry to hear you still have not found the help you needed.

As an alternative approach, would it not be simpler to ask the Proton for their DNS Provider IP addresses? That way you can enter them in Portmaster.

In my opinion, there are only 3 ways forward for now:

1. Disable DNS in ProtonVPN and configure your preferred service in Portmaster (ask Proton for their IP if you really want theirs, otherwise, I'd recommend Quad9 as a viable provider)
2. Uninstall Portmaster if (1.) is not an option.
3. Uninstall ProtonVPN and use SPN instead if both (1.) and (2.) are not an option.

I do not see any other solutions for the moment. Compatibility may be improved over the months and years, both from our end as well as VPN clients like ProtonVPN - but that discussion can be continued in https://github.com/safing/portmaster/issues/734. Feel free to continue commenting here, even if I am marking this as closed - since it is not a real issue
