### ISSUE TITLE
I am on Ubuntu 22.04

### ISSUE THREAD

**Issue by 226cenk** [safing/portmaster#812]
The "Open App" in the tray icon does not unhide the app. It worked fine a few weeks ago, it is suddenly not working. Portmaster itself seems to be functioning just fine, it's just. I can't open the GUI.

I've even tried killing the tasks associated with portmaster and tried restarting the app. The issue persists.

**Comment by 226cenk** [comment]
If by Gnome, you mean Ubuntu 22.04. Then yes, I am on Gnome.

**Comment by 226cenk** [comment]
There is a separate installation for the tray icon? Just installing the app worked fine for me till now. The tray icon for portmaster shows up, I just can't get the GUI to show up when I choose the option to show it.

How do I go about installing the tray icon.

**Comment by 226cenk** [comment]
Uh... will this 
'sudo apt install libnetfilter-queue1 libappindicator3-1'
from the safing.io work?

**Comment by 226cenk** [comment]
Do I just add the repo link into the 'Other software' tab of Software & Update

**Comment by davegson** [comment]
also in regards to:

> I can't open the GUI.

if you mean the Portmaster UI - we have received plenty of reports about this and are on it... the initial fix introduced other problems so the fix is receiving a fix ;)

**Comment by dhaavi** [comment]
Thank you for reporting this problem to us.

We are already investigating multiple reports about this or a similar issue.

To clarify what is happening exactly, please answer the following questions:
- Does the UI window load at all?
- From where did you start the UI? (Start Menu or Tray Icon?)
- If the UI window loads, what do you see?
- If you experience a "blank screen" in the UI window, was that the case immediately or after some time?
- Which OS are you using? If on Linux, are you using Wayland? (If you know what that is.)

In addition - if you can - please provide us some debugging information:
- If the UI window does not load at all, please provide the latest *.log and *.error.log files from C:\ProgramData\Safing\Portmaster\logs\app or /opt/safing/portmaster/logs/app
- If the UI window does load, please press F12 and copy any red-marked error message you see.

Thanks a lot for helping us to find this bug!

**Comment by 226cenk** [comment]
Both the start menu and tray icon. The tray icon starts up and is visible. Also, portmaster itself seems to be functioning fine. It's just the UI that is the issue. I try and click 'Open app' via the tray icon, it doesn't load the UI. I even tried to shutdown portmaster and start it back up via the start menu, the UI doesn't boot up.

Huh... seems to have fixed itself.... I am on Ubuntu 22.04, I don't have window's directories. Where would I go to find logs?

**Comment by OfficialEsco** [comment]
Hey, i just helped someone with this a few days ago, hopefully your issue is no longer there, but if it is your App Module is corrupt.
You can validate your Portmaster files with `/opt/safing/portmaster/portmaster-start --data /opt/safing/portmaster verify`
If that did not help you can try to delete the app module by deleting the files in `/opt/safing/portmaster/updates/all/linux_amd64/app/`
Once you've done that you can download the missing files by doing `/opt/safing/portmaster/portmaster-start --data /opt/safing/portmaster update`
At this point the Portmaster UI should open once you click "Open App" from the Tray bar or try to launch it from the App launcher.

Also to answer your question about log location, on Linux the path is `/opt/safing/portmaster/logs/` in there you can select the module you'd like the logs from.
According to the person i helped the app log looked just fine, but when removing the app module it did not even generate a log file, so I'd imagine there is a bug in the App Module.

**Comment by Raphty** [comment]
Thanks @OfficialEsco for the input, I also hope that that fixes a potential issue for anyone finding this.

If someone comes across this pleas open a new issue with the current info.
