### ISSUE TITLE
[FAQ] Why Portmaster Pings 1.1.1.1

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#817]

**Comment by dhaavi** [comment]
Not quite, but similar.

Portmaster never actually send a ping all the way to 1.1.1.1 - these are traceroute packages with low TTL values. Portmaster uses these to determine where on the Internet it is, without any server involved, and thus, maximum privacy.

In pretty much every case, the packet would never reach 1.1.1.1, but only your ISP.

1.1.1.1 is preferred over 9.9.9.9, as it is more common and it is easier to hide.

**Comment by Rexadev** [comment]
> Portmaster uses these to determine where on the Internet it is,

What
> without any server involved, and thus, maximum privacy.

What

> In pretty much every case, the packet would never reach 1.1.1.1, but only your ISP.

How? Why?

**Comment by Rexadev** [comment]
Should also use 9.9.9.9 and 8.8.8.8 as fallback
@dhaavi

**Comment by Rexadev** [comment]
> The Portmaster tries to identify it's location so it can choose a somewhat near entry-node into the SPN. Also, this serves as an online check so the PM knows if the device is online or not.

I dont use SPN

**Comment by ppacher** [comment]
Interesting since you complain about the SPN DNS Exit Node rules not being working....

Nevertheless, I'll discuss with the team if there's still a reason to try to identify the network location even if the SPN is not used. While I'm working on most of Portmaster core parts I'm not entirely sure if that check is required for captive portal detection. I'll post here as soon as I have more information on that.

**Comment by Rexadev** [comment]
> Interesting since you complain about the SPN DNS Exit Node rules not being working....

Sorry I misread the documentation and was in a hurry to report

**Comment by Rexadev** [comment]
@dhaavi you may close this
