### ISSUE TITLE
Total Security Suite

### ISSUE THREAD

**Issue by radumamy** [safing/portmaster#849]
Hi and thank you for your excellent work. Portmaster does feel like a nice polished Linux desktop firewall. I was wondering if there is any scope to add more features going forward such an antivirus/rootkit/malware scanner? It will be nice to have a complete open source Total Security solution (such as popular security tools sold for Windows OS). Or perhaps some sort of Advanced Threat Protection for end points where a singe UI can monitor different instances. I'm thinking something like clamav can run as agent/module for Portmaster. I am no expert, so please accept my apologies if this is not possible or unrealistic.
Thanks again.

**Comment by ppacher** [comment]
Hi @radumamy,

thanks for the kind words :)

Since we are a rather small team working on the Portmaster and the SPN things like antivirus scanning are definitely out of scope right now. We do have some threat-detection drafts lying around in some old branches but for the time being we have to focus on more important stuff that better fits the current scope/goal. 

That being said, I recently drafted a PR that adds external (third-party) plugin support to the Portmaster (in https://github.com/safing/portmaster/pull/834). That will allow the community to extend the feature-set of the Portmaster. I really like the idea of a clamav plugin that might scan binaries when they try to first connect to some server. Also, a central monitoring thingy could also be implemented as a plugin.

I'm already working on a plugin registry that will allow discovery and installation of available Portmaster plugins in https://github.com/ppacher/portmaster-plugin-registry. However, since this is **just a free-time project and not an official Safing product** it will still require some time to get a first working version. 
I created an [issue](https://github.com/ppacher/portmaster-plugin-registry/issues/1) in the registry repositry for that clamav idea. Let's see when I find some free time to draft something for that :)

I'll close this issue here now since things like that are out-of-scope for the official Safing Portmaster.
