### ISSUE TITLE
[Question] How to use DNS Exit Node Rules?

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#863]
I put 2 rules in it 
```
1. Allow -A country I am not in For Example - US
2. Block- *
```
In https://www.dnsleaktest.com/ I don' get the country I put in rules

**Comment by ppacher** [comment]
Please provide the debug information

**Comment by ppacher** [comment]
In https://github.com/safing/portmaster/issues/817#issuecomment-1255025045 you mentioned that you're not using the SPN.

As you can see in the UI, the DNS exit node feature is bound the the SPN (that's why it's below the SPN section). Also you only see that setting if you enabled the SPN.

I'm closing this here since you're obviously reporting a bug for something you don't even use. Please provide debug information because this way we would have been able to answer much earlier.
