### ISSUE TITLE
Some network not blocked for a totally blocked app

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#867]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
![image](https://user-images.githubusercontent.com/62152714/190916275-808d6cb0-8c19-444b-9e22-e65e66963b1f.png)
![image](https://user-images.githubusercontent.com/62152714/190916268-d92cce7b-14fc-43fc-b328-be9810de15ee.png)
Sorry Screenshot delted by mistake but trust me
![image](https://user-images.githubusercontent.com/62152714/191092601-1578472e-3cc7-4c6f-8bfa-f3d2b7eed59d.png)

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Rexadev** [comment]
> Maybe the connections were made before you changed settings?!

no

**Comment by ppacher** [comment]
Same thing as in #871. Those request never left the system as they were intercepted and handled by the Portmaster itself. That's why they are marked as internal and only shown in developer mode. Please do not create bugs for things you see in developer mode unless you really know what it's about because they are hidden on purpose.

Same answer from https://github.com/safing/portmaster/issues/871#issuecomment-1251924130 applies.
