### ISSUE TITLE
SNI Spoofing in DNS client

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#870]
Pros:
1. Privacy
2. Free Internet
Cons: 
1. Portmaster will appear on Internet as Criminals' App, Apps used to bypass restrictions
2. Make Network Management harder
3. Will not benefit Anyone. Will take Cat&Mouse game to the next level. People using it on PortMaster certainly not "need it"  and for people using it, it will not be useful anymore.

**What would you like to add or change?**:

**Why do you and others need this?**:

**Comment by ppacher** [comment]
SNI spoofing is not as easy to do because:

1.) You need to know which servers use one certificate for multiple websites in order to not get SSL verification issues
2.) The SNI can be encrypted which makes Spoofing useless as it cannot be intercepted anyway
3.) TLS session resumption avoid re-sending the SNI at all so spoofing isn't required there anyway.
4.) SNI spoofing is nothing that can be done system-wide by the Portmaster as this most likely needs to be implemented by the application that does the request.

Also I'm not sure what you mean with "Spoofing in DNS client". The SNI has nothing to do with DNS at all.
