### ISSUE TITLE
[Rules] Blocklist for DNS IPs and domains

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#876]
**What would you like to add or change?**:

**Why do you and others need this?**:
To prevent domain blocklist bypassing. Apps can use non DNS ports to resolve

**Comment by ppacher** [comment]
Not sure **What you would like to add or change**. Please eleborate

**Comment by Rexadev** [comment]
> To prevent domain blocklist bypassing. Apps can use non DNS ports to resolve

To block domains PortMaster has to resolve DNS by itself. A Malware can bypass domain blocklist if it uses it's own DNS.
For at Portmaster redirect port 53 and 853 to itself iirc?
I am suggesting to block all DNS domains and IPs because Malware can use non DNS ports to resolve

**Comment by ppacher** [comment]
Even if you would be able to maintain a list of all available DNS servers out there in the wild (which is nearly impossible) a malware author could just spin up it's own DNS server on an un-common port (which wouldn't be on the list then) or just hard code the IP address or just hand-roll a different protocol. 

In case a malware is able to otherwise get the IP address of a domain it want's to resolve it will still pop-up as a Peer-to-Peer connection because the Portmaster does not have seen a DNS query for that IP. So if you feel like this is something you want to be protected for, [Force Block P2P/Direct Connections](https://docs.safing.io/portmaster/settings#filter/blockP2P)
