### ISSUE TITLE
Run portmaster-core without downloading files

### ISSUE THREAD

**Issue by ghost** [safing/portmaster#882]
**What would you like to add or change?**:
When compiling portmaster yourself and starting portmaster-core with an empty data directory it downloads binaries and update information. This should only be done when it is necessary and no binaries are available or you deliberately activate automatic updates. You could move the update logic into portmaster-start and allow users to use portmaster-core without ever needing to download any files.

**Why do you and others need this?**:
The current way unnecessarily leaks information to your server by downloading files and creates files not needed when compiling the project yourself.

**Comment by dhaavi** [comment]
Hey @JackieWeiss, thanks for raising this with us.

If you do not want automatic updates, you can disable [Automatic Updates](https://docs.safing.io/portmaster/settings#core/automaticUpdates).

You can already run `portmaster-start update`.

The Portmaster Core Service should always download updates, as some of them are intelligence data which is needed for the protection to work properly.

The only information "leaked" to our update server is that someone downloaded updates. You can read our privacy policy about how careful we are with data.

Which files are "not needed"?

We are thinking about splitting the automatic update option into a "binaries" and a "intelligence data" option in the future.

**Comment by JackieWeiss** [comment]
I fully understand that I can disable Automatic updates but this is different because you cannot disable the fist download without opening the program and that downloads an update.

I also know I can run `portmaster-start update` but that was never my problem, my problem explicitly names the `portmaster-core` executable.

No, `portmaster-core` should never download some binaries or data without asking me or giving me an option to not do that for the first start, `portmaster-start update` exists for a reason. There is no way to prevent the very first download from happening.

The binaries are not needed. If I compile `portmaster-core` and run it there is absolutely zero reason for it to download another version of `portmaster-core`. I am currently running it. This download should only happen when I either run `portmaster-start core` or `portmaster-start update`. It also should not download the ui. I just ran `portmaster-core` I don't care about the ui files. This should only happen when I run `portmaster-start app` or `portmaster-start update`.

**Comment by ppacher** [comment]
Hi @JackieWeiss,

thanks for that write-up! I fully agree with you that we should not do automatic updates if the Portmaster is obviously started manually by the user!

I still feel that doing automatic download in portmaster-core is the only reasonable thing for doing automatic-binary updates but as you mentioned, that should likely only happen if launched by portmaster-start (which is the default for pkg-based installations).

I'll further discuss this with @dhaavi  as it feels like a simple solution to a broader auto-update based issue.
