### ISSUE TITLE
[Help] How to automatically update and combine blocklists into 1 file?

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#897]
Also Remove duplicates and sub-domain if domain is already there...

blocklist may have IPs domains subdomains

**Comment by dhaavi** [comment]
The duplicates are automatically removed on import, as the entries are saved in a hash map/dict.

Searching with https://duckduckgo.com/?q=combine+multiple+hosts+files&t=brave&ia=web brought me this:
- https://www.addictivetips.com/windows-tips/hostsman-edit-restore-manage-and-merge-multiple-windows-hosts-file/
- https://github.com/bornova/adblock-hosts

You possibly need to adapt a little, but I think merging these files is more common with hosts files.

If you are on linux just run this in the directory: `cat * > /path/to/combined/list`

Otherwise, let's see what the community can come up with!
