### ISSUE TITLE
Suggestion, I wish there was a function to manually add a process.

### ISSUE THREAD

**Issue by oklokl** [safing/portmaster#912]
**What would you like to add or change?**:
Manual Add Process button.
I want to manually register the process I want.
And for novice users, what if there was a button to allow your own country?.
Additionally, an AI function has been added. If there is a set menu that is frequently used in that country.. it would be better if it was provided in a recommended way.
AI services for first-time users. It is provided by the server and you can choose it according to your country.. My idea

AI automatically collects user settings for each country and recommends filters.
And the big data is stored on the server, and the singularities for each country are identified. characteristic.
We collect various information. only. If the user permits, this service may be provided. new button.

Developers fix bugs every time. Feedback on problems. can prevent you from doing it. The same kind of error problems are monitored by AI 24 hours a day.
through learning. Because it provides users. You can fix bugs and get users to access the correct website normally.
my idea.

It's Google Translate. Thank you for your understanding.

**Why do you and others need this?**:

If the user manually adds an undetectable process.
It seems to be able to solve compatibility issues.

I'm having a problem with the lol game and I'm still not able to solve it.
:)

For AI services. Anyone can easily access it by breaking away from the rough developer-style interface and rules, and it would be good for developers to analyze a lot of data and solve it easily.

**Comment by dhaavi** [comment]
Hey @oklokl, thanks for reporting this and going through the hassle of Google Translate. (You might have better result using DeepL.)

From what I understand you want to manually tell Portmaster about a process to help it detect and attribute connections. Unfortunately, this is not the problem for Portmaster when this happens. The problem is attribution - where no help is possible.

Can you elaborate on the problem you are having?

(About the other suggestion of collection data and auto-creating settings: Data collection is something we won't do, as it is deemed too hard to do privately. We however plan to source default settings from the community in the future.)

**Comment by oklokl** [comment]
#826 
I sent a mail. But I still couldn't solve it, so I came up with an idea to solve it myself.
If you can register manually...
I think the user can register the process.
When you register one by one. It seems that you can find things that are not detected and are processed as blocks.
Because 'Portmaster' is not omnipotent. It seems to be missing some process detection, not handling it.
If the user can register at this time, it seems to be able to provide wider compatibility.

And AI data analysis. It's annoying now though.
Create and use AI. If an interface is provided to the user through big data analysis, it seems that it will be more compatible and convenient arrangement.

It is very cumbersome as the developer guides and corrects whenever there is a problem. Customers seem to be having trouble leaving and leaving.
