### ISSUE TITLE
restart default dns-resolver after closing Portmaster

### ISSUE THREAD

**Issue by Raskaro** [safing/portmaster#93]
**What happened**:
After closing Portmaster, the DNS-Resolver is not restarted and therefore Name-Resolution doesn't work until you do a `sudo systemctl restart systemd-resolved`.

**What you expected to happen**:
The Linux-internal DNS-Resolver (which is made non-working by portmaster) is restored into a working state when closing Portmaster.

**How to reproduce it (as minimally and precisely as possible)**:
Open Portmaster, shutdown Portmaster, open a Website.

**Environment**:
Portmaster Version: v0.4.10 custom build

Operating System: Linux Mint 19.1 Cinnamon

**Comment by ppacher** [comment]
I'm not sure how we should fix that. We don't know what's the DNS server that the users wants to run, is it `systemd-resolved`, `dnsmasq`, `coredns`, `nextdns` or `dnscrypt` (just to name a few...)? Also, we don't know how the systemd unit service is called or if the user has created a custom one. What should we do on non-systemd systems?

I don't think that restaring the DNS resolver is feasible and we're likely jumping into a rabbit hole here. I'd rather discuss why the user expects that Portmaster will restart any other DNS server? IMHO that's because we stop (or actually kill) anything that was listening on port 53 before and the user wasn't responsible of switching.

IMHO that killing is the actual problem and it may also cause different issues like:

- We don't know if the service we're killing just does DNS or if it serves some other purpose as well like interface configuration (i.e. ConnMan).
- When switching wireless networks we might not pick up any local resolver changes because the DHCP client does not (or know how to) update the Portmaster.
- Just killing may result in the local service manager getting stuck into a restart loop trying to bring up the other DNS server again. In addition, systemctl for example will always report the system status as degraded because of that.

Although I understand that the Portmaster must be easily usable be the average user I think we are risking some "power-users" that cannot use it because it interferes with there local setup and they cannot change that behavior of Portmaster.

I'm not sure how the situation is on Windows but maybe we should re-think that service-killing at least on linux.

**Comment by ppacher** [comment]
Maybe we should support service takeover only for a handful of selected service where we know how to gracefully stop and restart them afterwards (and that we won't interfere with some other functionality). If the Portmaster discovers some unknown or unsupported service it should refuse to start and notify the user about the problem. I'd also add some command-line flag or environment variable to disable the hard takeover completely.

**Comment by dhaavi** [comment]
Created a new feature issue for this: https://github.com/safing/portmaster/issues/99

Closing for now.
