### ISSUE TITLE
 Windows Ring TopologyIs - Portmaster Kernel Extension?

### ISSUE THREAD

**Issue by LiberteIV** [safing/portmaster#980]
The Windows kernel uses a ring topology whereby only ring 0 has direct access to hardware. The OS protects this topology by only allowing bypass access to trusted/signed apps.

It's been more than 20 years since I learned this on a Microsoft course so my memory is hazy but, as far as I remember, peripheral ring layers (including network apps like PortMaster at ring 3) have absolutely no access to the kernel by default.

As a result, PortMaster has no more access to the guts of Windows than any other signed app. It may be implemented in a way that pleases you... but it cannot transcend the security of Windows' built-in ring topology.

If it could... then it would prove that Windows has absolutely no security at all.

**Comment by LiberteIV** [comment]
https://www.baeldung.com/cs/os-rings
![windows kernel ring topology](https://user-images.githubusercontent.com/116210112/200177442-da9de76c-591f-437c-928b-8a0f94d25674.png)

Portmaster is limited to ring 3, yes? no? how? why?

**Comment by vlabo** [comment]
This is a good question. I don't have deep understanding of the windows architecture but I will try to explain it as best as I can.

The Portmaster kernel extension in windows is basically a driver from Windows API term. Usually all major OSs the driver runs on lower ring level compared to an application which allows direct control of the hardware, as well as  other parts of the system and yes this has security issues but I don't think it's a major security flaw, since in order to install a driver you need administrative privileges and if you have admin account you have full control of the system anyway.

The Portmaster extension adds additional layer on top of the Windows networking stack that way it can filters and redirect traffic.

So as a whole the Portmaster system on windows has 3 parts:
 * Kernel extension runs on ring level less then 3.
 * Core service on ring 3 with admin privileges.
 * Ui on ring 3 as regular user.

[Here you can read a bit more about the architecture of Portmaster](https://github.com/safing/portmaster-windows-kext)

One more note about security, Microsoft requires all drivers to be signed by them in order to be installed.

Fill free to ask more questions if something is not clear enough.

**Comment by LiberteIV** [comment]
Thanks, interesting!

You mentioned kernel extension runs on ring level less then 3, that is a bit vague on where exactly, like ring 2, 1 or 0?

A note about signed drivers, i'm using nvcleanstall which is a program to install nvidia drivers without telemetry, there are some advanced settings which will result in an installation prompt saying driver signature not verified, install them anayways?
Appears to me, you can install drivers that are not signed, you just have to trust the source.

Might be wrong, might be not. I don't know the technical details.
