### ISSUE TITLE
Portmaster itself is missing in apps list

### ISSUE THREAD

**Issue by sprinesoo** [safing/portmaster#983]
**What happened**:
Portmaster itself is missing in apps list, even when i trigger update check.

**What did you expect to happen?**:
Portmaster should be listed in apps list.

**Comment by davegson** [comment]
you can see the Portmaster apps when setting your [UI Mode](https://docs.safing.io/portmaster/settings#core/expertiseLevel) to "Developer".

You can also read [all the details on the update system](https://docs.safing.io/portmaster/architecture/update-system) in case you are interested.

I would close this issue if you are OK with it too - please elaborate if this is unsatisfactory

**Comment by sprinesoo** [comment]
thank you for the explanation, i found everything! Its a trust thing for me, maybe its better to show portmaster components (i mean every app/service) by default to avoid irritations. The solution is ok for me, thank you very much again for the explanations!

**Comment by davegson** [comment]
I love the attitude to always question things. There are too many marketing deceptions out there, so trust should not be given just because of a promise. We are big believers of that.

> maybe its better to show portmaster components (i mean every app/service) by default to avoid irritations

I definitely understand this sentiment. At the same time the alternative would cause irritation too. Showing the three different Portmaster apps and expecting new users to understand what they are and do, when the current Portmaster can already be overwhelming for beginners... So while we are open to change it in the future, I believe for now it is OK to have it as is. 

Happy to hear you share that view too. Thanks for using Portmaster!
