### ISSUE TITLE
geo-unblocking not working - possibility to set an exit node for domains

### ISSUE THREAD

**Issue by crus234** [safing/portmaster#994]
**What would you like to add or change?**:
I am sitting in Austria and tried out the SPN/geo-unblocking feature. My expectation was that for sites like bbc.co.uk the UK node is used automatically to make sure that the site is "geo-unblocked". But this is not the case. I guess this is due to using the Austrian node for initial queries and the bbc site has CDN servers not only in the UK and therefore the UK node is not used as exit node. I would also be fine to set the exit node manually for specific pages but as long as this is not possible the service is not usable for me.

The second scenario are services based in my home country Austria. So if you e.g. open google.at with portmaster, it decides to use the french node as exit node which gives me a french Google site. I do understand that only using the Austrian node as entry and exit node is not preferable but getting a French page is also not an option. Again giving me the possibility to set an exit node would help. Even if the hopes are from Austria to France and back to Austria.

**Comment by astrophil04** [comment]
Same problem for me. I'm currently in Belgium doing some testing:
 1. For ZDF.de Portmaster uses the French exit node. 
 2. Connecting to the BBC results in using an Irish node. 
 3. Another problem: I can't watch Belgian public television, since there is no Belgian node (I circumvent the problem by using a different browser which I excluded from the SPN). So sometimes, more geoblocking issues occur.
 4. For https://tvthek.orf.at/ the Austrian node is chosen. Nevertheless the streams are blocked.

**Comment by remicorniere** [comment]
Hi ! Would you mind clarifying what type of input you expect ?
